# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from paigram_account_sdk._generated.platform.v1 import platform_pb2 as platform_dot_v1_dot_platform__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in platform/v1/platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlatformServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribePlatform = channel.unary_unary(
                '/paigram.platform.v1.PlatformService/DescribePlatform',
                request_serializer=platform_dot_v1_dot_platform__pb2.DescribePlatformRequest.SerializeToString,
                response_deserializer=platform_dot_v1_dot_platform__pb2.DescribePlatformResponse.FromString,
                _registered_method=True)
        self.GetCredentialSummary = channel.unary_unary(
                '/paigram.platform.v1.PlatformService/GetCredentialSummary',
                request_serializer=platform_dot_v1_dot_platform__pb2.GetCredentialSummaryRequest.SerializeToString,
                response_deserializer=platform_dot_v1_dot_platform__pb2.GetCredentialSummaryResponse.FromString,
                _registered_method=True)
        self.PutCredential = channel.unary_unary(
                '/paigram.platform.v1.PlatformService/PutCredential',
                request_serializer=platform_dot_v1_dot_platform__pb2.PutCredentialRequest.SerializeToString,
                response_deserializer=platform_dot_v1_dot_platform__pb2.PutCredentialResponse.FromString,
                _registered_method=True)
        self.RefreshCredential = channel.unary_unary(
                '/paigram.platform.v1.PlatformService/RefreshCredential',
                request_serializer=platform_dot_v1_dot_platform__pb2.RefreshCredentialRequest.SerializeToString,
                response_deserializer=platform_dot_v1_dot_platform__pb2.RefreshCredentialResponse.FromString,
                _registered_method=True)
        self.DeleteCredential = channel.unary_unary(
                '/paigram.platform.v1.PlatformService/DeleteCredential',
                request_serializer=platform_dot_v1_dot_platform__pb2.DeleteCredentialRequest.SerializeToString,
                response_deserializer=platform_dot_v1_dot_platform__pb2.DeleteCredentialResponse.FromString,
                _registered_method=True)
        self.InvalidateConsumerGrant = channel.unary_unary(
                '/paigram.platform.v1.PlatformService/InvalidateConsumerGrant',
                request_serializer=platform_dot_v1_dot_platform__pb2.InvalidateConsumerGrantRequest.SerializeToString,
                response_deserializer=platform_dot_v1_dot_platform__pb2.InvalidateConsumerGrantResponse.FromString,
                _registered_method=True)


class PlatformServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def DescribePlatform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredentialSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateConsumerGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribePlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribePlatform,
                    request_deserializer=platform_dot_v1_dot_platform__pb2.DescribePlatformRequest.FromString,
                    response_serializer=platform_dot_v1_dot_platform__pb2.DescribePlatformResponse.SerializeToString,
            ),
            'GetCredentialSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentialSummary,
                    request_deserializer=platform_dot_v1_dot_platform__pb2.GetCredentialSummaryRequest.FromString,
                    response_serializer=platform_dot_v1_dot_platform__pb2.GetCredentialSummaryResponse.SerializeToString,
            ),
            'PutCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.PutCredential,
                    request_deserializer=platform_dot_v1_dot_platform__pb2.PutCredentialRequest.FromString,
                    response_serializer=platform_dot_v1_dot_platform__pb2.PutCredentialResponse.SerializeToString,
            ),
            'RefreshCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshCredential,
                    request_deserializer=platform_dot_v1_dot_platform__pb2.RefreshCredentialRequest.FromString,
                    response_serializer=platform_dot_v1_dot_platform__pb2.RefreshCredentialResponse.SerializeToString,
            ),
            'DeleteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredential,
                    request_deserializer=platform_dot_v1_dot_platform__pb2.DeleteCredentialRequest.FromString,
                    response_serializer=platform_dot_v1_dot_platform__pb2.DeleteCredentialResponse.SerializeToString,
            ),
            'InvalidateConsumerGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateConsumerGrant,
                    request_deserializer=platform_dot_v1_dot_platform__pb2.InvalidateConsumerGrantRequest.FromString,
                    response_serializer=platform_dot_v1_dot_platform__pb2.InvalidateConsumerGrantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paigram.platform.v1.PlatformService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paigram.platform.v1.PlatformService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlatformService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DescribePlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v1.PlatformService/DescribePlatform',
            platform_dot_v1_dot_platform__pb2.DescribePlatformRequest.SerializeToString,
            platform_dot_v1_dot_platform__pb2.DescribePlatformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredentialSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v1.PlatformService/GetCredentialSummary',
            platform_dot_v1_dot_platform__pb2.GetCredentialSummaryRequest.SerializeToString,
            platform_dot_v1_dot_platform__pb2.GetCredentialSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v1.PlatformService/PutCredential',
            platform_dot_v1_dot_platform__pb2.PutCredentialRequest.SerializeToString,
            platform_dot_v1_dot_platform__pb2.PutCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v1.PlatformService/RefreshCredential',
            platform_dot_v1_dot_platform__pb2.RefreshCredentialRequest.SerializeToString,
            platform_dot_v1_dot_platform__pb2.RefreshCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v1.PlatformService/DeleteCredential',
            platform_dot_v1_dot_platform__pb2.DeleteCredentialRequest.SerializeToString,
            platform_dot_v1_dot_platform__pb2.DeleteCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateConsumerGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v1.PlatformService/InvalidateConsumerGrant',
            platform_dot_v1_dot_platform__pb2.InvalidateConsumerGrantRequest.SerializeToString,
            platform_dot_v1_dot_platform__pb2.InvalidateConsumerGrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
