// Package session is a thin session-issuing service used by handlers that
// authenticate users via OIDC flows (e.g. handler/telegramoidc).
//
// It deliberately does NOT replicate the full feature surface of
// handler/auth.Handler.issueSession (which also runs login-risk analysis,
// device tracking, suspicious-login email alerts, and Redis token caching).
// Those defenses target the username/password and provider-OAuth login
// paths where credentials live outside Telegram's trust boundary. For the
// Telegram OIDC flow the user has already authenticated with Telegram and
// re-authenticates whenever the session cookie is missing, so a minimal
// session row + HttpOnly cookie is the right surface.
//
// Refresh-token rotation is intentionally not supported by this service:
// no Refresh()/Rotate() entry point exists and no refresh material is
// returned to callers. OIDC-issued sessions expire and the user re-runs
// the Telegram OIDC flow to get a fresh cookie. Callers that need a
// rotating refresh token MUST use handler/auth.Handler.issueSession
// directly. The user_sessions.refresh_token_hash column is populated
// with an opaque, unmatchable nonce solely to satisfy the production
// `NOT NULL` + UNIQUE constraint on that column; the plaintext is
// discarded immediately and never returned, cached, or compared.
package session

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"gorm.io/gorm"

	"paigram/internal/model"
)

const (
	// SessionCookieName is the HttpOnly cookie carrying the raw access
	// token. The corresponding SHA-256 hash is stored on
	// user_sessions.access_token_hash, mirroring handler/auth's invariant
	// that plaintext access tokens never sit in the database.
	SessionCookieName = "ac_session"

	// defaultAccessTTL is the access-token cookie lifetime. There is no
	// refresh-rotation path for sessions issued by this service; the
	// user re-runs the OIDC flow when their cookie expires.
	defaultAccessTTL  = 15 * time.Minute
	defaultRefreshTTL = 7 * 24 * time.Hour

	accessTokenBytes = 48
)

// Service issues user sessions for OIDC-style login flows.
type Service struct {
	db     *gorm.DB
	logger *zap.Logger

	// accessTTL and refreshTTL allow callers (and tests) to override the
	// defaults. Zero values fall back to defaultAccessTTL /
	// defaultRefreshTTL. refreshTTL only affects the user_sessions row's
	// refresh_expiry column (kept for schema compatibility); no refresh
	// token is generated or returned by this service — see package doc.
	accessTTL  time.Duration
	refreshTTL time.Duration

	// secureCookie controls whether the Set-Cookie carries the Secure
	// attribute. Defaults to true; tests and local-HTTP development can
	// disable via WithSecureCookie(false).
	secureCookie bool
}

// Option configures a Service at construction time.
type Option func(*Service)

// WithAccessTTL overrides the access-token cookie / row lifetime.
func WithAccessTTL(d time.Duration) Option {
	return func(s *Service) {
		if d > 0 {
			s.accessTTL = d
		}
	}
}

// WithRefreshTTL overrides the user_sessions.refresh_expiry column
// lifetime. No refresh token is generated by this service; the column
// is populated so downstream cleanup jobs that scan by refresh_expiry
// still see a consistent value.
func WithRefreshTTL(d time.Duration) Option {
	return func(s *Service) {
		if d > 0 {
			s.refreshTTL = d
		}
	}
}

// WithSecureCookie toggles the Secure attribute on the session cookie.
// Production callers MUST leave this true (the default); tests + local
// HTTP-only dev override via WithSecureCookie(false).
func WithSecureCookie(secure bool) Option {
	return func(s *Service) {
		s.secureCookie = secure
	}
}

// NewService constructs a session-issuing Service backed by db. logger
// receives structured error logs on DB / cookie failures. Optional
// configuration via WithAccessTTL / WithRefreshTTL / WithSecureCookie.
func NewService(db *gorm.DB, logger *zap.Logger, opts ...Option) *Service {
	if logger == nil {
		logger = zap.NewNop()
	}
	s := &Service{
		db:           db,
		logger:       logger,
		accessTTL:    defaultAccessTTL,
		refreshTTL:   defaultRefreshTTL,
		secureCookie: true,
	}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// Issue creates a user_sessions row for userID and writes the access token
// as an HttpOnly Set-Cookie on c. The cookie's Max-Age matches the
// access-token TTL. See the package doc for why no refresh token is
// generated.
//
// Returns an error if the DB INSERT fails. A nil error means the session
// row was committed AND the cookie header was queued on the response.
//
// This is a backward-compatibility wrapper that opens its own short
// transaction and delegates to IssueTx. Callers that need to bundle the
// session insert into a larger transaction (e.g. handler/telegramoidc's
// Callback per spec §6.3) MUST call IssueTx with the outer tx.
func (s *Service) Issue(c *gin.Context, userID uint64) error {
	if c == nil {
		return fmt.Errorf("session: nil gin context")
	}
	return s.db.WithContext(c.Request.Context()).Transaction(func(tx *gorm.DB) error {
		return s.IssueTx(tx, c, userID)
	})
}

// IssueTx is the transaction-aware variant of Issue. It runs the
// user_sessions INSERT against the caller-supplied tx so a downstream
// failure in the outer tx (e.g. callback handler's later step) rolls
// the session row back. It MUST NOT call tx.Transaction(...) itself.
//
// Cookie ordering: the Set-Cookie header is written to c.Writer AFTER
// the DB INSERT succeeds but BEFORE IssueTx returns. The outer tx still
// commits after this point. Spec §6.3 has IssueTx as the LAST step in
// the wrapping transaction, so a post-IssueTx rollback would be a
// programming error in the caller (the cookie has already been queued
// on the response and would be sent to an unauthenticated client).
// Callers MUST ensure IssueTx is the final mutation before returning
// nil from the tx callback.
func (s *Service) IssueTx(tx *gorm.DB, c *gin.Context, userID uint64) error {
	if c == nil {
		return fmt.Errorf("session: nil gin context")
	}
	if userID == 0 {
		return fmt.Errorf("session: zero user id")
	}

	accessToken, err := randomToken(accessTokenBytes)
	if err != nil {
		s.logger.Error("session: random access token",
			zap.Uint64("user_id", userID), zap.Error(err))
		return fmt.Errorf("session: random access token: %w", err)
	}
	// Refresh-token hash placeholder: production user_sessions.refresh_token_hash
	// is `VARCHAR(64) NOT NULL` with `UNIQUE KEY uniq_refresh_token_hash`.
	// Writing the empty string would violate the UNIQUE constraint on the
	// second OIDC session in production. We generate an opaque nonce
	// solely to satisfy the constraint and discard the plaintext
	// immediately — no Refresh()/Rotate() entry point exists in this
	// service and the hash is never matched against any client-supplied
	// material. Callers needing real refresh-token rotation must use
	// handler/auth.Handler.issueSession; see package doc.
	noRefreshNonce, err := randomToken(accessTokenBytes)
	if err != nil {
		s.logger.Error("session: random refresh placeholder",
			zap.Uint64("user_id", userID), zap.Error(err))
		return fmt.Errorf("session: random refresh placeholder: %w", err)
	}

	now := time.Now().UTC()
	row := &model.UserSession{
		UserID:          userID,
		AccessTokenHash: hashToken(accessToken),
		// RefreshTokenHash holds an opaque, unmatchable nonce — see the
		// noRefreshNonce comment above and the package doc.
		RefreshTokenHash: hashToken(noRefreshNonce),
		AccessExpiry:     now.Add(s.accessTTL),
		RefreshExpiry:    now.Add(s.refreshTTL),
		UserAgent:        truncate(c.GetHeader("User-Agent"), 512),
		ClientIP:         c.ClientIP(),
	}
	if err := tx.WithContext(c.Request.Context()).Create(row).Error; err != nil {
		s.logger.Error("session: persist row",
			zap.Uint64("user_id", userID), zap.Error(err))
		return fmt.Errorf("session: persist row: %w", err)
	}

	// Explicit cookie attributes — going through http.SetCookie rather
	// than gin's c.SetCookie because the latter does not expose
	// SameSite. SameSite=Lax is required so the 302 redirect from
	// oauth.telegram.org back to /api/v1/auth/telegram/callback carries
	// the cookie (Strict would silently drop it on the cross-site
	// navigation; None requires Secure + would over-share).
	http.SetCookie(c.Writer, &http.Cookie{
		Name:     SessionCookieName,
		Value:    accessToken,
		Path:     "/",
		Domain:   "", // empty = scope to the request host
		MaxAge:   int(s.accessTTL.Seconds()),
		Secure:   s.secureCookie,
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
	})
	return nil
}

// --- helpers ---

// randomToken returns a URL-safe base64-encoded random string of size
// byteLen, with trailing '=' stripped to match handler/auth's convention.
func randomToken(byteLen int) (string, error) {
	buf := make([]byte, byteLen)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return strings.TrimRight(base64.RawURLEncoding.EncodeToString(buf), "="), nil
}

// hashToken returns the SHA-256 hex digest of token. We store hashes
// rather than plaintext so a DB read does not yield reusable credentials.
func hashToken(token string) string {
	if token == "" {
		return ""
	}
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

// truncate caps s at max bytes. Used to keep User-Agent / IP fields
// inside their column widths without panicking on overlong inputs.
func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max]
}
