package config

import (
	"fmt"
	"net/url"
	"strings"
	"sync"
	"time"

	"github.com/PaiGramTeam/paigram-account-center/contracts/runtime/go/secretfile"
	contractticket "github.com/PaiGramTeam/paigram-account-center/contracts/runtime/go/serviceticket"
	"github.com/PaiGramTeam/paigram-account-center/contracts/runtime/go/transporttls"
	"github.com/spf13/viper"
	"go.uber.org/zap"

	"paigram/internal/logging"
	telegramoidcsvc "paigram/internal/service/telegramoidc"
)

// Config aggregates application configuration sections.
type Config struct {
	App             AppConfig             `mapstructure:"app"`
	Database        DatabaseConfig        `mapstructure:"database"`
	OpenAPI         OpenAPIConfig         `mapstructure:"openapi"`
	Auth            AuthConfig            `mapstructure:"auth"`
	Frontend        FrontendConfig        `mapstructure:"frontend"`
	Redis           RedisConfig           `mapstructure:"redis"`
	GRPC            GRPCConfig            `mapstructure:"grpc"`
	PlatformControl PlatformControlConfig `mapstructure:"platform_control"`
	RateLimit       RateLimitConfig       `mapstructure:"rate_limit"`
	Email           EmailConfig           `mapstructure:"email"`
	Security        SecurityConfig        `mapstructure:"security"`
	Sentry          SentryConfig          `mapstructure:"sentry"`
	TelegramOIDC    TelegramOIDCConfig    `mapstructure:"telegram_oidc"`
}

// TelegramOIDCConfig holds the Telegram OIDC client credentials consumed
// by handler/telegramoidc + service/telegramoidc (Phase 5 Sub-project 1).
//
// All three fields are required when the feature is enabled. Leaving all
// three empty disables the /auth/telegram/* routes at boot — the handler
// ApiGroup simply is not constructed (see handler.InitializeApiGroups).
// Mixed empty/non-empty values are rejected by Config.Validate so a
// half-configured deployment fails fast at startup rather than 500-ing
// at request time.
//
// Spec: docs/superpowers/specs/2026-06-06-phase5-sub1-telegram-oidc-bot-link.md §5.5
type TelegramOIDCConfig struct {
	ClientID     string `mapstructure:"client_id"`
	ClientSecret string `mapstructure:"client_secret"`
	// RedirectURI must be the externally-reachable https URL of
	// GET /api/v1/auth/telegram/callback. The OIDC provider rejects
	// any deviation from the registered value.
	RedirectURI string `mapstructure:"redirect_uri"`

	// AuthorizeEndpoint, TokenEndpoint, JWKSEndpoint, and ExpectedIssuer
	// are a test-only seam (Phase 5 Sub-project 1 A7): they let the
	// integration suite point the OIDC client at a httptest.Server
	// mocking oauth.telegram.org. Production deployments MUST leave all
	// four empty so the underlying telegramoidcsvc.Config falls back to
	// the real oauth.telegram.org URLs via applyDefaults. The viper
	// mapstructure tags are intentionally absent — these fields are
	// populated only by in-process test code constructing a
	// *config.Config literal (see integration/telegram_oidc_test.go),
	// never by config files or env vars, and validateTelegramOIDCConfig
	// does NOT inspect them so a misconfigured production deployment
	// cannot accidentally override the real endpoints.
	AuthorizeEndpoint string `mapstructure:"-"`
	TokenEndpoint     string `mapstructure:"-"`
	JWKSEndpoint      string `mapstructure:"-"`
	ExpectedIssuer    string `mapstructure:"-"`
}

// FrontendConfig holds settings describing the user-facing frontend that
// receives links generated by this service (password reset, email
// verification, magic-link callbacks, etc.).
//
// BaseURL MUST be set in production. It is intentionally NOT derived from
// any request header (e.g. Origin/Referer/Host) because attacker-controlled
// headers would let a malicious caller redirect password-reset links to
// their own domain, leading to credential phishing. See V2 hardening.
type FrontendConfig struct {
	// BaseURL is the canonical externally-reachable URL of the frontend,
	// e.g. "https://app.example.com". Trailing slashes are normalized.
	BaseURL string `mapstructure:"base_url"`
}

// AppConfig holds HTTP server configuration.
type AppConfig struct {
	Name            string        `mapstructure:"name"`
	Host            string        `mapstructure:"host"`
	Port            int           `mapstructure:"port"`
	Mode            string        `mapstructure:"mode"`
	MaxBodyBytes    int64         `mapstructure:"max_body_bytes"`
	BodyReadTimeout time.Duration `mapstructure:"body_read_timeout"`
	TrustedProxies  []string      `mapstructure:"trusted_proxies"` // Trusted proxy CIDR ranges for X-Forwarded-For
	RealIPHeader    string        `mapstructure:"real_ip_header"`  // Custom header for real IP (e.g., "CF-Connecting-IP")
	IPv6Subnet      int           `mapstructure:"ipv6_subnet"`     // IPv6 subnet prefix length for rate limiting (default: 64)
	CORS            CORSConfig    `mapstructure:"cors"`
}

// CORSConfig holds HTTP CORS configuration.
type CORSConfig struct {
	Enabled             bool     `mapstructure:"enabled"`
	AllowOrigins        []string `mapstructure:"allow_origins"`
	AllowMethods        []string `mapstructure:"allow_methods"`
	AllowHeaders        []string `mapstructure:"allow_headers"`
	ExposeHeaders       []string `mapstructure:"expose_headers"`
	AllowCredentials    bool     `mapstructure:"allow_credentials"`
	AllowWildcard       bool     `mapstructure:"allow_wildcard"`
	AllowPrivateNetwork bool     `mapstructure:"allow_private_network"`
	MaxAgeSeconds       int      `mapstructure:"max_age"`
}

// DatabaseConfig holds PostgreSQL connection and pool configuration.
type DatabaseConfig struct {
	DSN             string        `mapstructure:"dsn"`
	DSNFile         string        `mapstructure:"dsn_file"`
	MigrationsDir   string        `mapstructure:"migrations_dir"`
	MaxIdleConns    int           `mapstructure:"max_idle_conns"`
	MaxOpenConns    int           `mapstructure:"max_open_conns"`
	ConnMaxLifetime time.Duration `mapstructure:"conn_max_lifetime"`
	ConnMaxIdleTime time.Duration `mapstructure:"conn_max_idle_time"`
	LogMode         string        `mapstructure:"log_mode"`
	LogZap          bool          `mapstructure:"log_zap"`
	SlowThreshold   int           `mapstructure:"slow_threshold"`
	AutoMigrate     bool          `mapstructure:"auto_migrate"`
	AutoSeed        bool          `mapstructure:"auto_seed"`
}

type OpenAPIConfig struct {
	Enabled bool   `mapstructure:"enabled"`
	Path    string `mapstructure:"path"`
}

// AuthConfig holds configuration for authentication flows.
type AuthConfig struct {
	AccessTokenTTLSeconds         int                            `mapstructure:"access_token_ttl"`
	RefreshTokenTTLSeconds        int                            `mapstructure:"refresh_token_ttl"`
	SessionUpdateAgeSeconds       int                            `mapstructure:"session_update_age"` // Auto-refresh threshold
	SessionFreshAgeSeconds        int                            `mapstructure:"session_fresh_age"`  // Freshness requirement for sensitive ops
	SessionCookieSecure           bool                           `mapstructure:"session_cookie_secure"`
	EmailVerificationTTLSeconds   int                            `mapstructure:"email_verification_ttl"`
	OAuthStateTTLSeconds          int                            `mapstructure:"oauth_state_ttl"`
	AllowedOAuthProviders         []string                       `mapstructure:"allowed_providers"`
	OAuthProviders                map[string]OAuthProviderConfig `mapstructure:"oauth"`
	DefaultOAuthRedirectURL       string                         `mapstructure:"default_oauth_redirect_url"`
	MaxConcurrentSessionsPerUser  int                            `mapstructure:"max_sessions_per_user"`
	PendingUserExpirySeconds      int                            `mapstructure:"pending_user_expiry"`
	PasswordResetTokenTTLSeconds  int                            `mapstructure:"password_reset_ttl"`
	RequireEmailVerificationLogin bool                           `mapstructure:"require_verified_email_login"`
	ServiceTicketTTLSeconds       int                            `mapstructure:"service_ticket_ttl"`
	ServiceTicketIssuer           string                         `mapstructure:"service_ticket_issuer"`
	ServiceTicketSigningKeyFile   string                         `mapstructure:"service_ticket_signing_key_file"`
	OAuthSigningKey               string                         `mapstructure:"oauth_signing_key"`
	OAuthSigningKeyFile           string                         `mapstructure:"oauth_signing_key_file"`
	// OAuthIssuer is the `iss` claim stamped onto every OAuth access
	// token issued by /oauth/token. Defaults to "account-center" — the
	// same string the gRPC interceptor's audience check expects.
	OAuthIssuer string `mapstructure:"oauth_issuer"`
	// OAuthAccessTokenTTLSeconds bounds the lifetime of issued OAuth
	// access tokens (Path D §1.6 — revocation = short TTL + credential
	// disable). Defaults to 3600 (1 hour).
	OAuthAccessTokenTTLSeconds int               `mapstructure:"oauth_access_token_ttl_seconds"`
	Captcha                    AuthCaptchaConfig `mapstructure:"captcha"`
}

// AuthCaptchaConfig holds CAPTCHA configuration for auth flows.
type AuthCaptchaConfig struct {
	Turnstile TurnstileConfig `mapstructure:"turnstile"`
}

// TurnstileConfig holds Cloudflare Turnstile verification settings.
type TurnstileConfig struct {
	Enabled                   bool   `mapstructure:"enabled"`
	SiteKey                   string `mapstructure:"site_key"`
	SecretKey                 string `mapstructure:"secret_key"`
	VerifyURL                 string `mapstructure:"verify_url"`
	ExpectedHostname          string `mapstructure:"expected_hostname"`
	RequireOnRegister         bool   `mapstructure:"require_on_register"`
	RequireOnLogin            bool   `mapstructure:"require_on_login"`
	LoginFailureThreshold     int    `mapstructure:"login_failure_threshold"`
	LoginFailureWindowSeconds int    `mapstructure:"login_failure_window"`
	RequestTimeoutSeconds     int    `mapstructure:"request_timeout"`
}

// OAuthProviderConfig models third-party provider credentials.
//
// Issuer and JWKSURL are required for OIDC providers (Google, etc.) so that
// id_tokens can be cryptographically verified. They are intentionally not
// inferred from the AuthURL — providers do not consistently expose a
// discoverable OIDC config and we never want to fall back to an unverified
// path. If a deployment forgets to configure these for a non-Telegram
// provider, OIDC verification will fail closed at runtime.
type OAuthProviderConfig struct {
	ClientID     string   `mapstructure:"client_id"`
	ClientSecret string   `mapstructure:"client_secret"`
	RedirectURL  string   `mapstructure:"redirect_url"`
	AuthURL      string   `mapstructure:"auth_url"`
	TokenURL     string   `mapstructure:"token_url"`
	UserInfoURL  string   `mapstructure:"user_info_url"`
	Issuer       string   `mapstructure:"issuer"`
	JWKSURL      string   `mapstructure:"jwks_url"`
	Scopes       []string `mapstructure:"scopes"`
}

// RedisConfig holds Redis connection and pooling behaviour.
type RedisConfig struct {
	Enabled      bool   `mapstructure:"enabled"`
	Addr         string `mapstructure:"addr"`
	Username     string `mapstructure:"username"`
	Password     string `mapstructure:"password"`
	PasswordFile string `mapstructure:"password_file"`
	DB           int    `mapstructure:"db"`
	Prefix       string `mapstructure:"prefix"`
	DialTimeout  int    `mapstructure:"dial_timeout"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	PoolSize     int    `mapstructure:"pool_size"`
	MinIdleConns int    `mapstructure:"min_idle_conns"`
	MaxRetries   int    `mapstructure:"max_retries"`
}

// GRPCConfig holds gRPC server configuration.
type GRPCConfig struct {
	Enabled               bool   `mapstructure:"enabled"`
	Port                  int    `mapstructure:"port"`
	MaxConnectionIdle     int    `mapstructure:"max_connection_idle"`
	MaxConnectionAge      int    `mapstructure:"max_connection_age"`
	MaxConnectionAgeGrace int    `mapstructure:"max_connection_age_grace"`
	KeepAliveTime         int    `mapstructure:"keepalive_time"`
	KeepAliveTimeout      int    `mapstructure:"keepalive_timeout"`
	CertificateFile       string `mapstructure:"certificate_file"`
	PrivateKeyFile        string `mapstructure:"private_key_file"`
}

type PlatformControlConfig struct {
	RootCAFile      string        `mapstructure:"root_ca_file"`
	CertificateFile string        `mapstructure:"certificate_file"`
	PrivateKeyFile  string        `mapstructure:"private_key_file"`
	ServerName      string        `mapstructure:"server_name"`
	DialTimeout     time.Duration `mapstructure:"dial_timeout"`
}

// RateLimitConfig holds rate limiting configuration.
type RateLimitConfig struct {
	Enabled bool                `mapstructure:"enabled"`
	Auth    RateLimitAuthConfig `mapstructure:"auth"`
	API     RateLimitAPIConfig  `mapstructure:"api"`
}

// RateLimitAuthConfig holds rate limits for authentication endpoints.
type RateLimitAuthConfig struct {
	Login        string `mapstructure:"login"`
	Register     string `mapstructure:"register"`
	VerifyEmail  string `mapstructure:"verify_email"`
	RefreshToken string `mapstructure:"refresh_token"`
	OAuth        string `mapstructure:"oauth"`
}

// RateLimitAPIConfig holds rate limits for API endpoints.
type RateLimitAPIConfig struct {
	Authenticated   string `mapstructure:"authenticated"`
	Unauthenticated string `mapstructure:"unauthenticated"`
}

// EmailConfig holds email service configuration.
type EmailConfig struct {
	Enabled       bool   `mapstructure:"enabled"`
	Provider      string `mapstructure:"provider"`      // smtp, sendgrid, mailgun, etc.
	SMTPHost      string `mapstructure:"smtp_host"`     // e.g., smtp.gmail.com
	SMTPPort      int    `mapstructure:"smtp_port"`     // e.g., 587
	SMTPUsername  string `mapstructure:"smtp_username"` // e.g., user@example.com
	SMTPPassword  string `mapstructure:"smtp_password"`
	FromEmail     string `mapstructure:"from_email"`     // Sender email address
	FromName      string `mapstructure:"from_name"`      // Sender name
	UseTLS        bool   `mapstructure:"use_tls"`        // Use TLS
	UseAsyncQueue bool   `mapstructure:"use_async"`      // Enable async sending queue
	QueueBackend  string `mapstructure:"queue_backend"`  // Queue backend: "memory" or "redis" (default: memory)
	QueueSize     int    `mapstructure:"queue_size"`     // Queue size for async sending
	Timeout       int    `mapstructure:"timeout"`        // SMTP timeout in seconds
	RetryAttempts int    `mapstructure:"retry_attempts"` // Number of retry attempts
	RetryDelay    int    `mapstructure:"retry_delay"`    // Delay between retries in seconds
	TemplateDir   string `mapstructure:"template_dir"`   // Directory for email templates (optional, uses embedded if empty)
}

// SecurityConfig holds security-related configuration.
type SecurityConfig struct {
	SuspiciousLoginDetection  bool                  `mapstructure:"suspicious_login_detection"`   // Enable suspicious login detection
	SuspiciousLoginEmailAlert bool                  `mapstructure:"suspicious_login_email_alert"` // Send email alerts for suspicious logins
	SecuritySettingsURL       string                `mapstructure:"security_settings_url"`        // URL to account security settings page
	BcryptCost                int                   `mapstructure:"bcrypt_cost"`                  // Bcrypt hashing cost (default: 12, min: 10, max: 31)
	RequireRedisFor2FA        bool                  `mapstructure:"require_redis_for_2fa"`        // V22: when true, 2FA rate limiting fails closed if Redis is unavailable
	TwoFAFailClosedTTL        time.Duration         `mapstructure:"twofa_fail_closed_ttl"`        // V22: lock duration applied when failing closed; defaults to 1m
	SecurityHeaders           SecurityHeadersConfig `mapstructure:"security_headers"`             // V10: HTTP response security headers
	// EncryptionKey is the resolved AES-256 master key used for 2FA secrets.
	EncryptionKey     string `mapstructure:"encryption_key"`
	EncryptionKeyFile string `mapstructure:"encryption_key_file"`
}

// SecurityHeadersConfig configures HTTP response security headers
// applied by the middleware in internal/middleware/security_headers.go
// (see V10).
type SecurityHeadersConfig struct {
	HSTSMaxAgeSeconds int    `mapstructure:"hsts_max_age_seconds"` // default 31536000 (1 year)
	HSTSIncludeSub    bool   `mapstructure:"hsts_include_sub"`     // default false; turning on is irrecoverable for the parent domain
	CSP               string `mapstructure:"csp"`                  // default "default-src 'self'"
	AssumeHTTPS       bool   `mapstructure:"assume_https"`         // default false; opt in ONLY when behind an HTTPS-terminating proxy. Header `X-Forwarded-Proto` is NOT honored because it is forgeable.
}

// SentryConfig holds Sentry error reporting configuration.
type SentryConfig struct {
	Enabled          bool    `mapstructure:"enabled"`
	DSN              string  `mapstructure:"dsn"`
	Environment      string  `mapstructure:"environment"`
	Release          string  `mapstructure:"release"`
	Debug            bool    `mapstructure:"debug"`
	AttachStacktrace bool    `mapstructure:"attach_stacktrace"`
	SampleRate       float64 `mapstructure:"sample_rate"`
	TracesSampleRate float64 `mapstructure:"traces_sample_rate"`
	FlushTimeout     int     `mapstructure:"flush_timeout"`
}

var (
	cfg     *Config
	cfgOnce sync.Once
)

// Load initializes configuration using Viper and returns a singleton instance.
// Subsequent calls reuse the loaded configuration.
func Load(paths ...string) (*Config, error) {
	var err error
	cfgOnce.Do(func() {
		v := viper.New()
		v.SetConfigName("config")
		v.SetConfigType("yaml")

		setDefaults(v)

		if len(paths) == 0 {
			v.AddConfigPath(".")
			v.AddConfigPath("./config")
			v.AddConfigPath("./configs")
		} else {
			for _, path := range paths {
				v.AddConfigPath(path)
			}
		}

		v.SetEnvPrefix("PAI")
		v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
		v.AutomaticEnv()

		if readErr := v.ReadInConfig(); readErr != nil {
			err = fmt.Errorf("read config: %w", readErr)
			return
		}

		localCfg := &Config{}
		if unmarshalErr := v.Unmarshal(localCfg); unmarshalErr != nil {
			err = fmt.Errorf("unmarshal config: %w", unmarshalErr)
			return
		}
		if secretErr := resolveSecretFiles(localCfg); secretErr != nil {
			err = secretErr
			return
		}
		if validateErr := validateServiceTicketConfig(localCfg); validateErr != nil {
			err = validateErr
			return
		}
		if validateErr := validateTelegramOIDCConfig(localCfg); validateErr != nil {
			err = validateErr
			return
		}
		if validateErr := validateEmailDeliveryConfig(localCfg); validateErr != nil {
			err = validateErr
			return
		}
		if validateErr := validateBrowserSessionConfig(localCfg); validateErr != nil {
			err = validateErr
			return
		}
		if validateErr := validatePlatformControlConfig(localCfg); validateErr != nil {
			err = validateErr
			return
		}
		if validateErr := validateGRPCServerConfig(localCfg); validateErr != nil {
			err = validateErr
			return
		}
		warnIfFrontendBaseURLMissing(localCfg)

		cfg = localCfg
	})

	if err != nil {
		Reset()
		return nil, err
	}

	if cfg == nil {
		return nil, fmt.Errorf("configuration not loaded")
	}
	return cfg, nil
}

func resolveSecretFiles(localCfg *Config) error {
	if localCfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	secretTargets := []struct {
		name string
		path string
		set  func(string)
	}{
		{name: "database.dsn_file", path: localCfg.Database.DSNFile, set: func(value string) { localCfg.Database.DSN = value }},
		{name: "redis.password_file", path: localCfg.Redis.PasswordFile, set: func(value string) { localCfg.Redis.Password = value }},
		{name: "auth.oauth_signing_key_file", path: localCfg.Auth.OAuthSigningKeyFile, set: func(value string) { localCfg.Auth.OAuthSigningKey = value }},
		{name: "security.encryption_key_file", path: localCfg.Security.EncryptionKeyFile, set: func(value string) { localCfg.Security.EncryptionKey = value }},
	}
	for _, target := range secretTargets {
		if target.path == "" {
			continue
		}
		value, err := secretfile.Read(target.path)
		if err != nil {
			return fmt.Errorf("%s: %w", target.name, err)
		}
		target.set(value)
	}
	return nil
}

func validatePlatformControlConfig(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	platform := cfg.PlatformControl
	if strings.TrimSpace(platform.ServerName) == "" {
		return fmt.Errorf("platform_control.server_name must not be empty")
	}
	if platform.DialTimeout <= 0 {
		return fmt.Errorf("platform_control.dial_timeout must be greater than zero")
	}
	if err := transporttls.ValidateClientFiles(transporttls.ClientFiles{
		RootCAFile:      platform.RootCAFile,
		CertificateFile: platform.CertificateFile,
		PrivateKeyFile:  platform.PrivateKeyFile,
		ServerName:      platform.ServerName,
	}, true); err != nil {
		return fmt.Errorf("platform_control TLS: %w", err)
	}
	return nil
}

func validateGRPCServerConfig(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	if !cfg.GRPC.Enabled {
		return nil
	}
	_, err := transporttls.NewServerConfig(transporttls.ServerFiles{
		CertificateFile: cfg.GRPC.CertificateFile,
		PrivateKeyFile:  cfg.GRPC.PrivateKeyFile,
	}, transporttls.ServerAuthOnly)
	if err != nil {
		return fmt.Errorf("grpc TLS: %w", err)
	}
	return nil
}

func validateServiceTicketConfig(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	auth := cfg.Auth
	if auth.ServiceTicketTTLSeconds <= 0 {
		return fmt.Errorf("auth.service_ticket_ttl must be greater than zero")
	}
	if auth.ServiceTicketIssuer == "" {
		return fmt.Errorf("auth.service_ticket_issuer must not be empty")
	}
	if auth.ServiceTicketTTLSeconds > 300 {
		return fmt.Errorf("auth.service_ticket_ttl must not exceed 300 seconds")
	}
	if _, err := contractticket.NewFileIssuer(contractticket.FileIssuerConfig{
		Issuer: auth.ServiceTicketIssuer, TTL: time.Duration(auth.ServiceTicketTTLSeconds) * time.Second,
		SigningKeyFile: auth.ServiceTicketSigningKeyFile,
	}); err != nil {
		return fmt.Errorf("auth.service_ticket_signing_key_file: %w", err)
	}
	if len(auth.OAuthSigningKey) < 32 {
		return fmt.Errorf("auth.oauth_signing_key must be at least 32 bytes")
	}
	return nil
}

func validateEmailDeliveryConfig(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	if !strings.EqualFold(strings.TrimSpace(cfg.App.Mode), "release") || !cfg.Auth.RequireEmailVerificationLogin {
		return nil
	}
	if !cfg.Email.Enabled {
		return fmt.Errorf("email.enabled must be true when release mode requires email verification")
	}
	frontendURL, err := url.Parse(strings.TrimSpace(cfg.Frontend.BaseURL))
	if err != nil || frontendURL.Scheme != "https" || frontendURL.Host == "" {
		return fmt.Errorf("frontend.base_url must be an absolute HTTPS URL when release mode requires email verification")
	}
	return nil
}

func validateBrowserSessionConfig(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	if !strings.EqualFold(strings.TrimSpace(cfg.App.Mode), "release") {
		return nil
	}
	if !cfg.Auth.SessionCookieSecure {
		return fmt.Errorf("auth.session_cookie_secure must be true in release mode")
	}
	frontendURL, err := url.Parse(strings.TrimSpace(cfg.Frontend.BaseURL))
	if err != nil || frontendURL.Scheme != "https" || frontendURL.Host == "" {
		return fmt.Errorf("frontend.base_url must be an absolute HTTPS URL in release mode")
	}
	return nil
}

// validateTelegramOIDCConfig enforces the all-or-nothing rule on
// telegram_oidc.{client_id, client_secret, redirect_uri}: leaving the
// whole block unset disables the feature (no error); setting any one
// of the three fields requires setting all three to a valid value.
//
// When set, the fields are passed through the service-layer
// telegramoidcsvc.Config.Validate (added in A2) so a single source of
// truth — telegramoidc/config.go — owns the actual rules (ClientID +
// ClientSecret non-empty, RedirectURI https).
//
// Spec: docs/superpowers/specs/2026-06-06-phase5-sub1-telegram-oidc-bot-link.md §5.5
func validateTelegramOIDCConfig(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	t := cfg.TelegramOIDC
	allEmpty := strings.TrimSpace(t.ClientID) == "" &&
		strings.TrimSpace(t.ClientSecret) == "" &&
		strings.TrimSpace(t.RedirectURI) == ""
	if allEmpty {
		// Feature disabled — handler.InitializeApiGroups skips OIDC
		// client construction and /auth/telegram/* routes 404 cleanly.
		return nil
	}
	svcCfg := &telegramoidcsvc.Config{
		ClientID:     t.ClientID,
		ClientSecret: t.ClientSecret,
		RedirectURI:  t.RedirectURI,
	}
	if err := svcCfg.Validate(); err != nil {
		return fmt.Errorf("config: telegram_oidc: %w", err)
	}
	return nil
}

// warnIfFrontendBaseURLMissing logs a warning when frontend.base_url is
// empty. We deliberately do NOT fail Load here — operators may run admin
// commands or migrations without a frontend, and breaking those flows over
// a missing URL would be hostile. The runtime password-reset path is
// already fail-closed: if BaseURL is empty it skips email send entirely
// (see V2 hardening in handler/auth/password_reset.go).
func warnIfFrontendBaseURLMissing(cfg *Config) {
	if cfg == nil {
		return
	}
	if strings.TrimSpace(cfg.Frontend.BaseURL) != "" {
		return
	}
	logging.Warn(
		"frontend.base_url is not configured; password-reset and similar emails will be suppressed",
		zap.String("setting", "frontend.base_url"),
	)
}

// MustLoad panics when configuration cannot be loaded.
func MustLoad(paths ...string) *Config {
	c, err := Load(paths...)
	if err != nil {
		panic(err)
	}
	return c
}

// Reset clears the Singleton (useful for tests).
func Reset() {
	cfg = nil
	cfgOnce = sync.Once{}
}

func setDefaults(v *viper.Viper) {
	// App defaults.
	// V21: trusted_proxies defaults to empty. Operators behind a reverse
	// proxy (k8s ingress, nginx, Cloudflare, etc.) MUST set this to the
	// proxy's real IP/CIDR. The previous default trusted all RFC1918
	// space, which let any host inside those CIDRs spoof X-Forwarded-For
	// and bypass IP-based rate limiting via c.ClientIP().
	v.SetDefault("app.trusted_proxies", []string{})
	v.SetDefault("app.real_ip_header", "") // Empty means use X-Forwarded-For via TrustedProxies
	v.SetDefault("app.ipv6_subnet", 64)    // /64 subnet (typical home/business allocation)
	v.SetDefault("app.cors.enabled", false)
	v.SetDefault("app.cors.allow_methods", []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"})
	v.SetDefault("app.cors.allow_headers", []string{"Origin", "Content-Type", "Accept", "Authorization"})
	v.SetDefault("app.cors.expose_headers", []string{})
	v.SetDefault("app.cors.allow_credentials", false)
	v.SetDefault("app.cors.allow_wildcard", false)
	v.SetDefault("app.cors.allow_private_network", false)
	v.SetDefault("app.cors.max_age", 43200)

	v.SetDefault("database.dsn", "")
	v.SetDefault("database.dsn_file", "")
	v.SetDefault("database.migrations_dir", "initialize/migrate/sql")
	v.SetDefault("database.max_idle_conns", 10)
	v.SetDefault("database.max_open_conns", 100)
	v.SetDefault("database.conn_max_lifetime", "1h")
	v.SetDefault("database.conn_max_idle_time", "30m")
	v.SetDefault("database.log_mode", "info")
	v.SetDefault("database.log_zap", true)
	v.SetDefault("database.slow_threshold", 1000)
	v.SetDefault("database.auto_migrate", true)
	v.SetDefault("database.auto_seed", true)
	v.SetDefault("openapi.enabled", true)
	v.SetDefault("openapi.path", "/openapi")

	v.SetDefault("auth.access_token_ttl", 900)
	v.SetDefault("auth.refresh_token_ttl", 604800)
	v.SetDefault("auth.session_cookie_secure", false)
	v.SetDefault("auth.email_verification_ttl", 86400)
	v.SetDefault("auth.oauth_state_ttl", 300)
	v.SetDefault("auth.allowed_providers", []string{"github", "google", "telegram"})
	v.SetDefault("auth.default_oauth_redirect_url", "http://localhost:8080/api/v1/auth/oauth/callback")
	v.SetDefault("auth.max_sessions_per_user", 10)
	v.SetDefault("auth.pending_user_expiry", 2592000)
	v.SetDefault("auth.password_reset_ttl", 3600)
	v.SetDefault("auth.require_verified_email_login", true)
	v.SetDefault("auth.service_ticket_ttl", 300)
	v.SetDefault("auth.service_ticket_issuer", "paigram-account-center")
	v.SetDefault("auth.service_ticket_signing_key_file", "")
	v.SetDefault("auth.oauth_signing_key", "")
	v.SetDefault("auth.oauth_signing_key_file", "")
	// Path D §3.2 + §1.6: OAuth 2.0 client_credentials defaults. Issuer
	// matches the gRPC interceptor's audience-check constant
	// (machineTokenAudience = "account-center"). 3600-second TTL is the
	// happy-medium between revocation latency and refresh churn.
	v.SetDefault("auth.oauth_issuer", "account-center")
	v.SetDefault("auth.oauth_access_token_ttl_seconds", 3600)
	v.SetDefault("auth.captcha.turnstile.enabled", false)
	v.SetDefault("auth.captcha.turnstile.verify_url", "https://challenges.cloudflare.com/turnstile/v0/siteverify")
	v.SetDefault("auth.captcha.turnstile.require_on_register", true)
	v.SetDefault("auth.captcha.turnstile.require_on_login", false)
	v.SetDefault("auth.captcha.turnstile.login_failure_threshold", 3)
	v.SetDefault("auth.captcha.turnstile.login_failure_window", 900)
	v.SetDefault("auth.captcha.turnstile.request_timeout", 5)

	// Frontend defaults: empty BaseURL by design — production deployments
	// must override this via config or env (PAI_FRONTEND_BASE_URL). Leaving
	// it empty causes the password-reset path to log + skip email rather
	// than fall back to an attacker-controlled Origin header. See V2.
	v.SetDefault("frontend.base_url", "")

	v.SetDefault("redis.enabled", false)
	v.SetDefault("redis.addr", "127.0.0.1:6379")
	v.SetDefault("redis.password_file", "")
	v.SetDefault("redis.db", 0)
	v.SetDefault("redis.prefix", "paigram")
	v.SetDefault("redis.dial_timeout", 5)
	v.SetDefault("redis.read_timeout", 3)
	v.SetDefault("redis.write_timeout", 3)
	v.SetDefault("redis.pool_size", 20)
	v.SetDefault("redis.min_idle_conns", 5)
	v.SetDefault("redis.max_retries", 2)
	v.SetDefault("platform_control.root_ca_file", "")
	v.SetDefault("platform_control.certificate_file", "")
	v.SetDefault("platform_control.private_key_file", "")
	v.SetDefault("platform_control.server_name", "")
	v.SetDefault("platform_control.dial_timeout", "5s")
	v.SetDefault("grpc.certificate_file", "")
	v.SetDefault("grpc.private_key_file", "")

	v.SetDefault("rate_limit.enabled", true)
	v.SetDefault("rate_limit.auth.login", "5-M")
	v.SetDefault("rate_limit.auth.register", "3-H")
	v.SetDefault("rate_limit.auth.verify_email", "10-H")
	v.SetDefault("rate_limit.auth.refresh_token", "10-M")
	v.SetDefault("rate_limit.auth.oauth", "10-M")
	v.SetDefault("rate_limit.api.authenticated", "1000-H")
	v.SetDefault("rate_limit.api.unauthenticated", "100-H")

	v.SetDefault("email.enabled", false)
	v.SetDefault("email.provider", "smtp")
	v.SetDefault("email.smtp_host", "smtp.gmail.com")
	v.SetDefault("email.smtp_port", 587)
	v.SetDefault("email.from_email", "noreply@paigram.com")
	v.SetDefault("email.from_name", "PaiGram")
	v.SetDefault("email.use_tls", true)
	v.SetDefault("email.use_async", true)
	v.SetDefault("email.retry_attempts", 3)
	v.SetDefault("email.retry_delay", 5)

	v.SetDefault("security.bcrypt_cost", 12)
	v.SetDefault("security.suspicious_login_detection", false)
	v.SetDefault("security.suspicious_login_email_alert", false)
	// V22: fail closed by default. Operators who run a single instance
	// without Redis can opt out by setting require_redis_for_2fa: false.
	v.SetDefault("security.require_redis_for_2fa", true)
	v.SetDefault("security.encryption_key_file", "")
	v.SetDefault("security.twofa_fail_closed_ttl", "1m")
	// V10: response security headers. HSTS subdomain inclusion stays off
	// by default — turning it on is irrecoverable for the parent domain
	// for the duration of max-age. assume_https is also off by default;
	// X-Forwarded-Proto is intentionally NOT honored (it is forgeable
	// when no proxy filter is in place), so operators behind an
	// HTTPS-terminating proxy must opt in explicitly.
	v.SetDefault("security.security_headers.hsts_max_age_seconds", 31536000)
	v.SetDefault("security.security_headers.hsts_include_sub", false)
	v.SetDefault("security.security_headers.csp", "default-src 'self'")
	v.SetDefault("security.security_headers.assume_https", false)

	v.SetDefault("sentry.enabled", false)
	v.SetDefault("sentry.dsn", "")
	v.SetDefault("sentry.environment", "development")
	v.SetDefault("sentry.release", "")
	v.SetDefault("sentry.debug", false)
	v.SetDefault("sentry.attach_stacktrace", true)
	v.SetDefault("sentry.sample_rate", 1.0)
	v.SetDefault("sentry.traces_sample_rate", 0.0)
	v.SetDefault("sentry.flush_timeout", 2)

	// Phase 5 Sub-project 1: Telegram OIDC credentials. Defaults are
	// empty strings — leaving the block unset disables the feature
	// (validateTelegramOIDCConfig short-circuits). When operators DO
	// opt in, the typical path is the PAI_TELEGRAM_OIDC_* env vars
	// (mapped automatically by SetEnvPrefix("PAI") + the dot->underscore
	// key replacer above). The SetDefault calls below are required so
	// viper actually consults the env vars even when no config.yaml key
	// is present — without an explicit default, viper.AutomaticEnv
	// silently ignores keys it doesn't already know about.
	v.SetDefault("telegram_oidc.client_id", "")
	v.SetDefault("telegram_oidc.client_secret", "")
	v.SetDefault("telegram_oidc.redirect_uri", "")
}

// GetBcryptCost returns the bcrypt cost with validation
// Returns a safe value between 10 and 14 (default: 12)
func (c *Config) GetBcryptCost() int {
	cost := c.Security.BcryptCost
	if cost < 10 {
		return 12 // Default: OWASP recommended minimum
	}
	if cost > 14 {
		return 14 // Cap at 14 to prevent DoS (14 takes ~1.5 seconds)
	}
	return cost
}
