DROP TABLE IF EXISTS audit_events CASCADE;
DROP TRIGGER IF EXISTS active_administrator_guard_user_roles ON user_roles;
DROP TRIGGER IF EXISTS active_administrator_guard_users_update ON users;
DROP TRIGGER IF EXISTS active_administrator_guard_users_delete ON users;
DROP TRIGGER IF EXISTS active_administrator_guard_roles_update ON roles;
DROP TRIGGER IF EXISTS active_administrator_guard_roles_delete ON roles;
DROP TRIGGER IF EXISTS active_administrator_guard_role_permissions ON role_permissions;
DROP TRIGGER IF EXISTS active_administrator_guard_permissions_update ON permissions;
DROP TRIGGER IF EXISTS active_administrator_guard_permissions_delete ON permissions;
DROP TRIGGER IF EXISTS active_administrator_guard_casbin_rules ON casbin_rule;
DROP TRIGGER IF EXISTS admin_guard_prevent_delete ON admin_guard;
DROP FUNCTION IF EXISTS prevent_admin_guard_removal();
DROP FUNCTION IF EXISTS enforce_active_administrator_guard();
DROP FUNCTION IF EXISTS validate_active_administrator_guard();
DROP TABLE IF EXISTS admin_guard CASCADE;
DROP TABLE IF EXISTS legal_documents CASCADE;
DROP TABLE IF EXISTS system_config_entries CASCADE;
DROP TABLE IF EXISTS consumer_grant_actions CASCADE;
DROP TABLE IF EXISTS consumer_grants CASCADE;
DROP FUNCTION IF EXISTS enforce_consumer_grant_actions_from_action();
DROP FUNCTION IF EXISTS enforce_consumer_grant_actions_from_grant();
DROP FUNCTION IF EXISTS validate_consumer_grant_actions(BIGINT);
DROP TABLE IF EXISTS platform_account_profiles CASCADE;
DROP TABLE IF EXISTS platform_account_bindings CASCADE;
DROP TABLE IF EXISTS platform_services CASCADE;
DROP TABLE IF EXISTS service_credentials CASCADE;
DROP TABLE IF EXISTS bot_identities CASCADE;
DROP TABLE IF EXISTS bots CASCADE;
DROP TABLE IF EXISTS casbin_rule CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS login_logs CASCADE;
DROP TABLE IF EXISTS user_devices CASCADE;
DROP TABLE IF EXISTS user_two_factors CASCADE;
DROP TABLE IF EXISTS login_audits CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS user_oauth_states CASCADE;
DROP TABLE IF EXISTS user_emails CASCADE;
DROP TABLE IF EXISTS user_credentials CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
