// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bot_access.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformAccountStatus int32

const (
	PlatformAccountStatus_PLATFORM_ACCOUNT_STATUS_UNSPECIFIED PlatformAccountStatus = 0
	PlatformAccountStatus_PLATFORM_ACCOUNT_STATUS_ACTIVE      PlatformAccountStatus = 1
	PlatformAccountStatus_PLATFORM_ACCOUNT_STATUS_INACTIVE    PlatformAccountStatus = 2
	PlatformAccountStatus_PLATFORM_ACCOUNT_STATUS_REVOKED     PlatformAccountStatus = 3
)

// Enum value maps for PlatformAccountStatus.
var (
	PlatformAccountStatus_name = map[int32]string{
		0: "PLATFORM_ACCOUNT_STATUS_UNSPECIFIED",
		1: "PLATFORM_ACCOUNT_STATUS_ACTIVE",
		2: "PLATFORM_ACCOUNT_STATUS_INACTIVE",
		3: "PLATFORM_ACCOUNT_STATUS_REVOKED",
	}
	PlatformAccountStatus_value = map[string]int32{
		"PLATFORM_ACCOUNT_STATUS_UNSPECIFIED": 0,
		"PLATFORM_ACCOUNT_STATUS_ACTIVE":      1,
		"PLATFORM_ACCOUNT_STATUS_INACTIVE":    2,
		"PLATFORM_ACCOUNT_STATUS_REVOKED":     3,
	}
)

func (x PlatformAccountStatus) Enum() *PlatformAccountStatus {
	p := new(PlatformAccountStatus)
	*p = x
	return p
}

func (x PlatformAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_access_proto_enumTypes[0].Descriptor()
}

func (PlatformAccountStatus) Type() protoreflect.EnumType {
	return &file_bot_access_proto_enumTypes[0]
}

func (x PlatformAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformAccountStatus.Descriptor instead.
func (PlatformAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{0}
}

type PlatformAccountBinding struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform           string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformServiceKey string                 `protobuf:"bytes,4,opt,name=platform_service_key,json=platformServiceKey,proto3" json:"platform_service_key,omitempty"`
	PlatformAccountId  string                 `protobuf:"bytes,5,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	DisplayName        string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status             PlatformAccountStatus  `protobuf:"varint,7,opt,name=status,proto3,enum=paigram.v1.PlatformAccountStatus" json:"status,omitempty"`
	MetaJson           string                 `protobuf:"bytes,8,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlatformAccountBinding) Reset() {
	*x = PlatformAccountBinding{}
	mi := &file_bot_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformAccountBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformAccountBinding) ProtoMessage() {}

func (x *PlatformAccountBinding) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformAccountBinding.ProtoReflect.Descriptor instead.
func (*PlatformAccountBinding) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformAccountBinding) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlatformAccountBinding) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlatformAccountBinding) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformAccountBinding) GetPlatformServiceKey() string {
	if x != nil {
		return x.PlatformServiceKey
	}
	return ""
}

func (x *PlatformAccountBinding) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *PlatformAccountBinding) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PlatformAccountBinding) GetStatus() PlatformAccountStatus {
	if x != nil {
		return x.Status
	}
	return PlatformAccountStatus_PLATFORM_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *PlatformAccountBinding) GetMetaJson() string {
	if x != nil {
		return x.MetaJson
	}
	return ""
}

func (x *PlatformAccountBinding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlatformAccountBinding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ResolveBotUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveBotUserRequest) Reset() {
	*x = ResolveBotUserRequest{}
	mi := &file_bot_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBotUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBotUserRequest) ProtoMessage() {}

func (x *ResolveBotUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBotUserRequest.ProtoReflect.Descriptor instead.
func (*ResolveBotUserRequest) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveBotUserRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

type ResolveBotUserResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BotId            string                 `protobuf:"bytes,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ExternalUserId   string                 `protobuf:"bytes,3,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	ExternalUsername string                 `protobuf:"bytes,4,opt,name=external_username,json=externalUsername,proto3" json:"external_username,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveBotUserResponse) Reset() {
	*x = ResolveBotUserResponse{}
	mi := &file_bot_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBotUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBotUserResponse) ProtoMessage() {}

func (x *ResolveBotUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBotUserResponse.ProtoReflect.Descriptor instead.
func (*ResolveBotUserResponse) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveBotUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResolveBotUserResponse) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ResolveBotUserResponse) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *ResolveBotUserResponse) GetExternalUsername() string {
	if x != nil {
		return x.ExternalUsername
	}
	return ""
}

// UpsertPlatformBinding is a legacy migration-only RPC.
// Normal bot runtime must use ResolveBotUser, ListAccessibleBindings,
// and IssueServiceTicket instead of creating or updating bindings.
type UpsertPlatformBindingRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId     string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	Platform           string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformServiceKey string                 `protobuf:"bytes,3,opt,name=platform_service_key,json=platformServiceKey,proto3" json:"platform_service_key,omitempty"`
	PlatformAccountId  string                 `protobuf:"bytes,4,opt,name=platform_account_id,json=platformAccountId,proto3" json:"platform_account_id,omitempty"`
	DisplayName        string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	MetaJson           string                 `protobuf:"bytes,6,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`
	GrantScopes        []string               `protobuf:"bytes,7,rep,name=grant_scopes,json=grantScopes,proto3" json:"grant_scopes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpsertPlatformBindingRequest) Reset() {
	*x = UpsertPlatformBindingRequest{}
	mi := &file_bot_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPlatformBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPlatformBindingRequest) ProtoMessage() {}

func (x *UpsertPlatformBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPlatformBindingRequest.ProtoReflect.Descriptor instead.
func (*UpsertPlatformBindingRequest) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertPlatformBindingRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *UpsertPlatformBindingRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpsertPlatformBindingRequest) GetPlatformServiceKey() string {
	if x != nil {
		return x.PlatformServiceKey
	}
	return ""
}

func (x *UpsertPlatformBindingRequest) GetPlatformAccountId() string {
	if x != nil {
		return x.PlatformAccountId
	}
	return ""
}

func (x *UpsertPlatformBindingRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpsertPlatformBindingRequest) GetMetaJson() string {
	if x != nil {
		return x.MetaJson
	}
	return ""
}

func (x *UpsertPlatformBindingRequest) GetGrantScopes() []string {
	if x != nil {
		return x.GrantScopes
	}
	return nil
}

type UpsertPlatformBindingResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Binding       *PlatformAccountBinding `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	Created       bool                    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPlatformBindingResponse) Reset() {
	*x = UpsertPlatformBindingResponse{}
	mi := &file_bot_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPlatformBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPlatformBindingResponse) ProtoMessage() {}

func (x *UpsertPlatformBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPlatformBindingResponse.ProtoReflect.Descriptor instead.
func (*UpsertPlatformBindingResponse) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertPlatformBindingResponse) GetBinding() *PlatformAccountBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *UpsertPlatformBindingResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ListAccessibleBindingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	Platform       string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAccessibleBindingsRequest) Reset() {
	*x = ListAccessibleBindingsRequest{}
	mi := &file_bot_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessibleBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessibleBindingsRequest) ProtoMessage() {}

func (x *ListAccessibleBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessibleBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListAccessibleBindingsRequest) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccessibleBindingsRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *ListAccessibleBindingsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ListAccessibleBindingsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Bindings      []*PlatformAccountBinding `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessibleBindingsResponse) Reset() {
	*x = ListAccessibleBindingsResponse{}
	mi := &file_bot_access_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessibleBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessibleBindingsResponse) ProtoMessage() {}

func (x *ListAccessibleBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessibleBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListAccessibleBindingsResponse) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{6}
}

func (x *ListAccessibleBindingsResponse) GetBindings() []*PlatformAccountBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type IssueServiceTicketRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId  string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	BindingId       uint64                 `protobuf:"varint,2,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	RequestedScopes []string               `protobuf:"bytes,3,rep,name=requested_scopes,json=requestedScopes,proto3" json:"requested_scopes,omitempty"`
	Audience        string                 `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	ProfileId       uint64                 `protobuf:"varint,5,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueServiceTicketRequest) Reset() {
	*x = IssueServiceTicketRequest{}
	mi := &file_bot_access_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueServiceTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueServiceTicketRequest) ProtoMessage() {}

func (x *IssueServiceTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueServiceTicketRequest.ProtoReflect.Descriptor instead.
func (*IssueServiceTicketRequest) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{7}
}

func (x *IssueServiceTicketRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *IssueServiceTicketRequest) GetBindingId() uint64 {
	if x != nil {
		return x.BindingId
	}
	return 0
}

func (x *IssueServiceTicketRequest) GetRequestedScopes() []string {
	if x != nil {
		return x.RequestedScopes
	}
	return nil
}

func (x *IssueServiceTicketRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *IssueServiceTicketRequest) GetProfileId() uint64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type IssueServiceTicketResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Ticket        string                  `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Audience      string                  `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	ExpiresAt     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Binding       *PlatformAccountBinding `protobuf:"bytes,4,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueServiceTicketResponse) Reset() {
	*x = IssueServiceTicketResponse{}
	mi := &file_bot_access_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueServiceTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueServiceTicketResponse) ProtoMessage() {}

func (x *IssueServiceTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_access_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueServiceTicketResponse.ProtoReflect.Descriptor instead.
func (*IssueServiceTicketResponse) Descriptor() ([]byte, []int) {
	return file_bot_access_proto_rawDescGZIP(), []int{8}
}

func (x *IssueServiceTicketResponse) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *IssueServiceTicketResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *IssueServiceTicketResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *IssueServiceTicketResponse) GetBinding() *PlatformAccountBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

var File_bot_access_proto protoreflect.FileDescriptor

const file_bot_access_proto_rawDesc = "" +
	"\n" +
	"\x10bot_access.proto\x12\n" +
	"paigram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"\x16PlatformAccountBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x120\n" +
	"\x14platform_service_key\x18\x04 \x01(\tR\x12platformServiceKey\x12.\n" +
	"\x13platform_account_id\x18\x05 \x01(\tR\x11platformAccountId\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.paigram.v1.PlatformAccountStatusR\x06status\x12\x1b\n" +
	"\tmeta_json\x18\b \x01(\tR\bmetaJson\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"A\n" +
	"\x15ResolveBotUserRequest\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\"\x9f\x01\n" +
	"\x16ResolveBotUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\tR\x05botId\x12(\n" +
	"\x10external_user_id\x18\x03 \x01(\tR\x0eexternalUserId\x12+\n" +
	"\x11external_username\x18\x04 \x01(\tR\x10externalUsername\"\xa9\x02\n" +
	"\x1cUpsertPlatformBindingRequest\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x120\n" +
	"\x14platform_service_key\x18\x03 \x01(\tR\x12platformServiceKey\x12.\n" +
	"\x13platform_account_id\x18\x04 \x01(\tR\x11platformAccountId\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tmeta_json\x18\x06 \x01(\tR\bmetaJson\x12!\n" +
	"\fgrant_scopes\x18\a \x03(\tR\vgrantScopes\"w\n" +
	"\x1dUpsertPlatformBindingResponse\x12<\n" +
	"\abinding\x18\x01 \x01(\v2\".paigram.v1.PlatformAccountBindingR\abinding\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"e\n" +
	"\x1dListAccessibleBindingsRequest\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"`\n" +
	"\x1eListAccessibleBindingsResponse\x12>\n" +
	"\bbindings\x18\x01 \x03(\v2\".paigram.v1.PlatformAccountBindingR\bbindings\"\xca\x01\n" +
	"\x19IssueServiceTicketRequest\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x02 \x01(\x04R\tbindingId\x12)\n" +
	"\x10requested_scopes\x18\x03 \x03(\tR\x0frequestedScopes\x12\x1a\n" +
	"\baudience\x18\x04 \x01(\tR\baudience\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x05 \x01(\x04R\tprofileId\"\xc9\x01\n" +
	"\x1aIssueServiceTicketResponse\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\abinding\x18\x04 \x01(\v2\".paigram.v1.PlatformAccountBindingR\abinding*\xaf\x01\n" +
	"\x15PlatformAccountStatus\x12'\n" +
	"#PLATFORM_ACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1ePLATFORM_ACCOUNT_STATUS_ACTIVE\x10\x01\x12$\n" +
	" PLATFORM_ACCOUNT_STATUS_INACTIVE\x10\x02\x12#\n" +
	"\x1fPLATFORM_ACCOUNT_STATUS_REVOKED\x10\x032\xaf\x03\n" +
	"\x10BotAccessService\x12W\n" +
	"\x0eResolveBotUser\x12!.paigram.v1.ResolveBotUserRequest\x1a\".paigram.v1.ResolveBotUserResponse\x12l\n" +
	"\x15UpsertPlatformBinding\x12(.paigram.v1.UpsertPlatformBindingRequest\x1a).paigram.v1.UpsertPlatformBindingResponse\x12o\n" +
	"\x16ListAccessibleBindings\x12).paigram.v1.ListAccessibleBindingsRequest\x1a*.paigram.v1.ListAccessibleBindingsResponse\x12c\n" +
	"\x12IssueServiceTicket\x12%.paigram.v1.IssueServiceTicketRequest\x1a&.paigram.v1.IssueServiceTicketResponseB Z\x1epaigram/internal/grpc/pb/v1;pbb\x06proto3"

var (
	file_bot_access_proto_rawDescOnce sync.Once
	file_bot_access_proto_rawDescData []byte
)

func file_bot_access_proto_rawDescGZIP() []byte {
	file_bot_access_proto_rawDescOnce.Do(func() {
		file_bot_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_access_proto_rawDesc), len(file_bot_access_proto_rawDesc)))
	})
	return file_bot_access_proto_rawDescData
}

var file_bot_access_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bot_access_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bot_access_proto_goTypes = []any{
	(PlatformAccountStatus)(0),             // 0: paigram.v1.PlatformAccountStatus
	(*PlatformAccountBinding)(nil),         // 1: paigram.v1.PlatformAccountBinding
	(*ResolveBotUserRequest)(nil),          // 2: paigram.v1.ResolveBotUserRequest
	(*ResolveBotUserResponse)(nil),         // 3: paigram.v1.ResolveBotUserResponse
	(*UpsertPlatformBindingRequest)(nil),   // 4: paigram.v1.UpsertPlatformBindingRequest
	(*UpsertPlatformBindingResponse)(nil),  // 5: paigram.v1.UpsertPlatformBindingResponse
	(*ListAccessibleBindingsRequest)(nil),  // 6: paigram.v1.ListAccessibleBindingsRequest
	(*ListAccessibleBindingsResponse)(nil), // 7: paigram.v1.ListAccessibleBindingsResponse
	(*IssueServiceTicketRequest)(nil),      // 8: paigram.v1.IssueServiceTicketRequest
	(*IssueServiceTicketResponse)(nil),     // 9: paigram.v1.IssueServiceTicketResponse
	(*timestamppb.Timestamp)(nil),          // 10: google.protobuf.Timestamp
}
var file_bot_access_proto_depIdxs = []int32{
	0,  // 0: paigram.v1.PlatformAccountBinding.status:type_name -> paigram.v1.PlatformAccountStatus
	10, // 1: paigram.v1.PlatformAccountBinding.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: paigram.v1.PlatformAccountBinding.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: paigram.v1.UpsertPlatformBindingResponse.binding:type_name -> paigram.v1.PlatformAccountBinding
	1,  // 4: paigram.v1.ListAccessibleBindingsResponse.bindings:type_name -> paigram.v1.PlatformAccountBinding
	10, // 5: paigram.v1.IssueServiceTicketResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 6: paigram.v1.IssueServiceTicketResponse.binding:type_name -> paigram.v1.PlatformAccountBinding
	2,  // 7: paigram.v1.BotAccessService.ResolveBotUser:input_type -> paigram.v1.ResolveBotUserRequest
	4,  // 8: paigram.v1.BotAccessService.UpsertPlatformBinding:input_type -> paigram.v1.UpsertPlatformBindingRequest
	6,  // 9: paigram.v1.BotAccessService.ListAccessibleBindings:input_type -> paigram.v1.ListAccessibleBindingsRequest
	8,  // 10: paigram.v1.BotAccessService.IssueServiceTicket:input_type -> paigram.v1.IssueServiceTicketRequest
	3,  // 11: paigram.v1.BotAccessService.ResolveBotUser:output_type -> paigram.v1.ResolveBotUserResponse
	5,  // 12: paigram.v1.BotAccessService.UpsertPlatformBinding:output_type -> paigram.v1.UpsertPlatformBindingResponse
	7,  // 13: paigram.v1.BotAccessService.ListAccessibleBindings:output_type -> paigram.v1.ListAccessibleBindingsResponse
	9,  // 14: paigram.v1.BotAccessService.IssueServiceTicket:output_type -> paigram.v1.IssueServiceTicketResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_bot_access_proto_init() }
func file_bot_access_proto_init() {
	if File_bot_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_access_proto_rawDesc), len(file_bot_access_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_access_proto_goTypes,
		DependencyIndexes: file_bot_access_proto_depIdxs,
		EnumInfos:         file_bot_access_proto_enumTypes,
		MessageInfos:      file_bot_access_proto_msgTypes,
	}.Build()
	File_bot_access_proto = out.File
	file_bot_access_proto_goTypes = nil
	file_bot_access_proto_depIdxs = nil
}
