// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bot_route.proto

package pb

import (
	v1 "github.com/PaiGramTeam/proto-contracts/bot/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterBotServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable bot identifier, e.g. "paigrambot".
	BotId string `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// Platform key, e.g. "telegram" / "matrix".
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// Business service identifier, e.g. "paigram-genshin".
	ServiceId string `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// gRPC dial target, e.g. "paigram-genshin:50052".
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// SemVer of the business service for observability.
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Declared command handlers exposed by the service.
	Handlers      []*v1.HandlerDeclaration `protobuf:"bytes,6,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBotServiceRequest) Reset() {
	*x = RegisterBotServiceRequest{}
	mi := &file_bot_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBotServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBotServiceRequest) ProtoMessage() {}

func (x *RegisterBotServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBotServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterBotServiceRequest) Descriptor() ([]byte, []int) {
	return file_bot_route_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterBotServiceRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *RegisterBotServiceRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterBotServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterBotServiceRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterBotServiceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterBotServiceRequest) GetHandlers() []*v1.HandlerDeclaration {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type RegisterBotServiceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RegisteredAtUnix int64                  `protobuf:"varint,1,opt,name=registered_at_unix,json=registeredAtUnix,proto3" json:"registered_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterBotServiceResponse) Reset() {
	*x = RegisterBotServiceResponse{}
	mi := &file_bot_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBotServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBotServiceResponse) ProtoMessage() {}

func (x *RegisterBotServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBotServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterBotServiceResponse) Descriptor() ([]byte, []int) {
	return file_bot_route_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterBotServiceResponse) GetRegisteredAtUnix() int64 {
	if x != nil {
		return x.RegisteredAtUnix
	}
	return 0
}

type UnregisterBotServiceRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BotId    string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Platform string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// service_id is used as a sanity check to confirm the caller is releasing
	// the route it actually owns.
	ServiceId     string `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterBotServiceRequest) Reset() {
	*x = UnregisterBotServiceRequest{}
	mi := &file_bot_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterBotServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterBotServiceRequest) ProtoMessage() {}

func (x *UnregisterBotServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterBotServiceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterBotServiceRequest) Descriptor() ([]byte, []int) {
	return file_bot_route_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterBotServiceRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *UnregisterBotServiceRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UnregisterBotServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type UnregisterBotServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterBotServiceResponse) Reset() {
	*x = UnregisterBotServiceResponse{}
	mi := &file_bot_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterBotServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterBotServiceResponse) ProtoMessage() {}

func (x *UnregisterBotServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterBotServiceResponse.ProtoReflect.Descriptor instead.
func (*UnregisterBotServiceResponse) Descriptor() ([]byte, []int) {
	return file_bot_route_proto_rawDescGZIP(), []int{3}
}

type GetBotRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotRouteRequest) Reset() {
	*x = GetBotRouteRequest{}
	mi := &file_bot_route_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotRouteRequest) ProtoMessage() {}

func (x *GetBotRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_route_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotRouteRequest.ProtoReflect.Descriptor instead.
func (*GetBotRouteRequest) Descriptor() ([]byte, []int) {
	return file_bot_route_proto_rawDescGZIP(), []int{4}
}

func (x *GetBotRouteRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *GetBotRouteRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GetBotRouteResponse struct {
	state               protoimpl.MessageState   `protogen:"open.v1"`
	ServiceId           string                   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Endpoint            string                   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Version             string                   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Handlers            []*v1.HandlerDeclaration `protobuf:"bytes,4,rep,name=handlers,proto3" json:"handlers,omitempty"`
	LastHeartbeatAtUnix int64                    `protobuf:"varint,5,opt,name=last_heartbeat_at_unix,json=lastHeartbeatAtUnix,proto3" json:"last_heartbeat_at_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetBotRouteResponse) Reset() {
	*x = GetBotRouteResponse{}
	mi := &file_bot_route_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotRouteResponse) ProtoMessage() {}

func (x *GetBotRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_route_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotRouteResponse.ProtoReflect.Descriptor instead.
func (*GetBotRouteResponse) Descriptor() ([]byte, []int) {
	return file_bot_route_proto_rawDescGZIP(), []int{5}
}

func (x *GetBotRouteResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetBotRouteResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *GetBotRouteResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetBotRouteResponse) GetHandlers() []*v1.HandlerDeclaration {
	if x != nil {
		return x.Handlers
	}
	return nil
}

func (x *GetBotRouteResponse) GetLastHeartbeatAtUnix() int64 {
	if x != nil {
		return x.LastHeartbeatAtUnix
	}
	return 0
}

var File_bot_route_proto protoreflect.FileDescriptor

const file_bot_route_proto_rawDesc = "" +
	"\n" +
	"\x0fbot_route.proto\x12\n" +
	"paigram.v1\x1a\x14bot/v1/handler.proto\"\xe3\x01\n" +
	"\x19RegisterBotServiceRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12>\n" +
	"\bhandlers\x18\x06 \x03(\v2\".paigram.bot.v1.HandlerDeclarationR\bhandlers\"J\n" +
	"\x1aRegisterBotServiceResponse\x12,\n" +
	"\x12registered_at_unix\x18\x01 \x01(\x03R\x10registeredAtUnix\"o\n" +
	"\x1bUnregisterBotServiceRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\"\x1e\n" +
	"\x1cUnregisterBotServiceResponse\"G\n" +
	"\x12GetBotRouteRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"\xdf\x01\n" +
	"\x13GetBotRouteResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12>\n" +
	"\bhandlers\x18\x04 \x03(\v2\".paigram.bot.v1.HandlerDeclarationR\bhandlers\x123\n" +
	"\x16last_heartbeat_at_unix\x18\x05 \x01(\x03R\x13lastHeartbeatAtUnix2\xb1\x02\n" +
	"\x0fBotRouteService\x12c\n" +
	"\x12RegisterBotService\x12%.paigram.v1.RegisterBotServiceRequest\x1a&.paigram.v1.RegisterBotServiceResponse\x12i\n" +
	"\x14UnregisterBotService\x12'.paigram.v1.UnregisterBotServiceRequest\x1a(.paigram.v1.UnregisterBotServiceResponse\x12N\n" +
	"\vGetBotRoute\x12\x1e.paigram.v1.GetBotRouteRequest\x1a\x1f.paigram.v1.GetBotRouteResponseB Z\x1epaigram/internal/grpc/pb/v1;pbb\x06proto3"

var (
	file_bot_route_proto_rawDescOnce sync.Once
	file_bot_route_proto_rawDescData []byte
)

func file_bot_route_proto_rawDescGZIP() []byte {
	file_bot_route_proto_rawDescOnce.Do(func() {
		file_bot_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_route_proto_rawDesc), len(file_bot_route_proto_rawDesc)))
	})
	return file_bot_route_proto_rawDescData
}

var file_bot_route_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bot_route_proto_goTypes = []any{
	(*RegisterBotServiceRequest)(nil),    // 0: paigram.v1.RegisterBotServiceRequest
	(*RegisterBotServiceResponse)(nil),   // 1: paigram.v1.RegisterBotServiceResponse
	(*UnregisterBotServiceRequest)(nil),  // 2: paigram.v1.UnregisterBotServiceRequest
	(*UnregisterBotServiceResponse)(nil), // 3: paigram.v1.UnregisterBotServiceResponse
	(*GetBotRouteRequest)(nil),           // 4: paigram.v1.GetBotRouteRequest
	(*GetBotRouteResponse)(nil),          // 5: paigram.v1.GetBotRouteResponse
	(*v1.HandlerDeclaration)(nil),        // 6: paigram.bot.v1.HandlerDeclaration
}
var file_bot_route_proto_depIdxs = []int32{
	6, // 0: paigram.v1.RegisterBotServiceRequest.handlers:type_name -> paigram.bot.v1.HandlerDeclaration
	6, // 1: paigram.v1.GetBotRouteResponse.handlers:type_name -> paigram.bot.v1.HandlerDeclaration
	0, // 2: paigram.v1.BotRouteService.RegisterBotService:input_type -> paigram.v1.RegisterBotServiceRequest
	2, // 3: paigram.v1.BotRouteService.UnregisterBotService:input_type -> paigram.v1.UnregisterBotServiceRequest
	4, // 4: paigram.v1.BotRouteService.GetBotRoute:input_type -> paigram.v1.GetBotRouteRequest
	1, // 5: paigram.v1.BotRouteService.RegisterBotService:output_type -> paigram.v1.RegisterBotServiceResponse
	3, // 6: paigram.v1.BotRouteService.UnregisterBotService:output_type -> paigram.v1.UnregisterBotServiceResponse
	5, // 7: paigram.v1.BotRouteService.GetBotRoute:output_type -> paigram.v1.GetBotRouteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bot_route_proto_init() }
func file_bot_route_proto_init() {
	if File_bot_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_route_proto_rawDesc), len(file_bot_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_route_proto_goTypes,
		DependencyIndexes: file_bot_route_proto_depIdxs,
		MessageInfos:      file_bot_route_proto_msgTypes,
	}.Build()
	File_bot_route_proto = out.File
	file_bot_route_proto_goTypes = nil
	file_bot_route_proto_depIdxs = nil
}
