// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: bot_route.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotRouteService_RegisterBotService_FullMethodName   = "/paigram.v1.BotRouteService/RegisterBotService"
	BotRouteService_UnregisterBotService_FullMethodName = "/paigram.v1.BotRouteService/UnregisterBotService"
	BotRouteService_GetBotRoute_FullMethodName          = "/paigram.v1.BotRouteService/GetBotRoute"
)

// BotRouteServiceClient is the client API for BotRouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BotRouteService manages the registry mapping (bot_id, platform) to a
// currently-active game-service endpoint. Telegram dispatch reads this routing
// table to forward incoming updates to the correct downstream service.
type BotRouteServiceClient interface {
	// Called by a game-service on start up, on heartbeat and on handler changes.
	RegisterBotService(ctx context.Context, in *RegisterBotServiceRequest, opts ...grpc.CallOption) (*RegisterBotServiceResponse, error)
	// Called by a game-service on graceful shutdown to release the route.
	UnregisterBotService(ctx context.Context, in *UnregisterBotServiceRequest, opts ...grpc.CallOption) (*UnregisterBotServiceResponse, error)
	// Called by telegram-service on startup and on periodic refresh.
	GetBotRoute(ctx context.Context, in *GetBotRouteRequest, opts ...grpc.CallOption) (*GetBotRouteResponse, error)
}

type botRouteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotRouteServiceClient(cc grpc.ClientConnInterface) BotRouteServiceClient {
	return &botRouteServiceClient{cc}
}

func (c *botRouteServiceClient) RegisterBotService(ctx context.Context, in *RegisterBotServiceRequest, opts ...grpc.CallOption) (*RegisterBotServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBotServiceResponse)
	err := c.cc.Invoke(ctx, BotRouteService_RegisterBotService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botRouteServiceClient) UnregisterBotService(ctx context.Context, in *UnregisterBotServiceRequest, opts ...grpc.CallOption) (*UnregisterBotServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterBotServiceResponse)
	err := c.cc.Invoke(ctx, BotRouteService_UnregisterBotService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botRouteServiceClient) GetBotRoute(ctx context.Context, in *GetBotRouteRequest, opts ...grpc.CallOption) (*GetBotRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBotRouteResponse)
	err := c.cc.Invoke(ctx, BotRouteService_GetBotRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotRouteServiceServer is the server API for BotRouteService service.
// All implementations must embed UnimplementedBotRouteServiceServer
// for forward compatibility.
//
// BotRouteService manages the registry mapping (bot_id, platform) to a
// currently-active game-service endpoint. Telegram dispatch reads this routing
// table to forward incoming updates to the correct downstream service.
type BotRouteServiceServer interface {
	// Called by a game-service on start up, on heartbeat and on handler changes.
	RegisterBotService(context.Context, *RegisterBotServiceRequest) (*RegisterBotServiceResponse, error)
	// Called by a game-service on graceful shutdown to release the route.
	UnregisterBotService(context.Context, *UnregisterBotServiceRequest) (*UnregisterBotServiceResponse, error)
	// Called by telegram-service on startup and on periodic refresh.
	GetBotRoute(context.Context, *GetBotRouteRequest) (*GetBotRouteResponse, error)
	mustEmbedUnimplementedBotRouteServiceServer()
}

// UnimplementedBotRouteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotRouteServiceServer struct{}

func (UnimplementedBotRouteServiceServer) RegisterBotService(context.Context, *RegisterBotServiceRequest) (*RegisterBotServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBotService not implemented")
}
func (UnimplementedBotRouteServiceServer) UnregisterBotService(context.Context, *UnregisterBotServiceRequest) (*UnregisterBotServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterBotService not implemented")
}
func (UnimplementedBotRouteServiceServer) GetBotRoute(context.Context, *GetBotRouteRequest) (*GetBotRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBotRoute not implemented")
}
func (UnimplementedBotRouteServiceServer) mustEmbedUnimplementedBotRouteServiceServer() {}
func (UnimplementedBotRouteServiceServer) testEmbeddedByValue()                         {}

// UnsafeBotRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotRouteServiceServer will
// result in compilation errors.
type UnsafeBotRouteServiceServer interface {
	mustEmbedUnimplementedBotRouteServiceServer()
}

func RegisterBotRouteServiceServer(s grpc.ServiceRegistrar, srv BotRouteServiceServer) {
	// If the following call panics, it indicates UnimplementedBotRouteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotRouteService_ServiceDesc, srv)
}

func _BotRouteService_RegisterBotService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBotServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotRouteServiceServer).RegisterBotService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotRouteService_RegisterBotService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotRouteServiceServer).RegisterBotService(ctx, req.(*RegisterBotServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotRouteService_UnregisterBotService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterBotServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotRouteServiceServer).UnregisterBotService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotRouteService_UnregisterBotService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotRouteServiceServer).UnregisterBotService(ctx, req.(*UnregisterBotServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotRouteService_GetBotRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotRouteServiceServer).GetBotRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotRouteService_GetBotRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotRouteServiceServer).GetBotRoute(ctx, req.(*GetBotRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotRouteService_ServiceDesc is the grpc.ServiceDesc for BotRouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotRouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paigram.v1.BotRouteService",
	HandlerType: (*BotRouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBotService",
			Handler:    _BotRouteService_RegisterBotService_Handler,
		},
		{
			MethodName: "UnregisterBotService",
			Handler:    _BotRouteService_UnregisterBotService_Handler,
		},
		{
			MethodName: "GetBotRoute",
			Handler:    _BotRouteService_GetBotRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot_route.proto",
}
