// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.1
// source: proto/paigram/v1/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误代码
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT    ErrorCode = 1
	ErrorCode_ERROR_CODE_NOT_FOUND           ErrorCode = 2
	ErrorCode_ERROR_CODE_ALREADY_EXISTS      ErrorCode = 3
	ErrorCode_ERROR_CODE_PERMISSION_DENIED   ErrorCode = 4
	ErrorCode_ERROR_CODE_UNAUTHENTICATED     ErrorCode = 5
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED  ErrorCode = 6
	ErrorCode_ERROR_CODE_FAILED_PRECONDITION ErrorCode = 7
	ErrorCode_ERROR_CODE_ABORTED             ErrorCode = 8
	ErrorCode_ERROR_CODE_INTERNAL            ErrorCode = 9
	ErrorCode_ERROR_CODE_UNAVAILABLE         ErrorCode = 10
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_ARGUMENT",
		2:  "ERROR_CODE_NOT_FOUND",
		3:  "ERROR_CODE_ALREADY_EXISTS",
		4:  "ERROR_CODE_PERMISSION_DENIED",
		5:  "ERROR_CODE_UNAUTHENTICATED",
		6:  "ERROR_CODE_RESOURCE_EXHAUSTED",
		7:  "ERROR_CODE_FAILED_PRECONDITION",
		8:  "ERROR_CODE_ABORTED",
		9:  "ERROR_CODE_INTERNAL",
		10: "ERROR_CODE_UNAVAILABLE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_INVALID_ARGUMENT":    1,
		"ERROR_CODE_NOT_FOUND":           2,
		"ERROR_CODE_ALREADY_EXISTS":      3,
		"ERROR_CODE_PERMISSION_DENIED":   4,
		"ERROR_CODE_UNAUTHENTICATED":     5,
		"ERROR_CODE_RESOURCE_EXHAUSTED":  6,
		"ERROR_CODE_FAILED_PRECONDITION": 7,
		"ERROR_CODE_ABORTED":             8,
		"ERROR_CODE_INTERNAL":            9,
		"ERROR_CODE_UNAVAILABLE":         10,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paigram_v1_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_paigram_v1_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_paigram_v1_common_proto_rawDescGZIP(), []int{0}
}

// 分页请求
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Desc          bool                   `protobuf:"varint,4,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_proto_paigram_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PageRequest) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// 分页响应
type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_proto_paigram_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_proto_paigram_v1_common_proto protoreflect.FileDescriptor

const file_proto_paigram_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/paigram/v1/common.proto\x12\n" +
	"paigram.v1\"k\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\bR\x04desc\"v\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages*\xd7\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x03\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x04\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x05\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\x06\x12\"\n" +
	"\x1eERROR_CODE_FAILED_PRECONDITION\x10\a\x12\x16\n" +
	"\x12ERROR_CODE_ABORTED\x10\b\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\t\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\n" +
	"B Z\x1epaigram/internal/grpc/pb/v1;pbb\x06proto3"

var (
	file_proto_paigram_v1_common_proto_rawDescOnce sync.Once
	file_proto_paigram_v1_common_proto_rawDescData []byte
)

func file_proto_paigram_v1_common_proto_rawDescGZIP() []byte {
	file_proto_paigram_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_paigram_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paigram_v1_common_proto_rawDesc), len(file_proto_paigram_v1_common_proto_rawDesc)))
	})
	return file_proto_paigram_v1_common_proto_rawDescData
}

var file_proto_paigram_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_paigram_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_paigram_v1_common_proto_goTypes = []any{
	(ErrorCode)(0),       // 0: paigram.v1.ErrorCode
	(*PageRequest)(nil),  // 1: paigram.v1.PageRequest
	(*PageResponse)(nil), // 2: paigram.v1.PageResponse
}
var file_proto_paigram_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_paigram_v1_common_proto_init() }
func file_proto_paigram_v1_common_proto_init() {
	if File_proto_paigram_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paigram_v1_common_proto_rawDesc), len(file_proto_paigram_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_paigram_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_paigram_v1_common_proto_depIdxs,
		EnumInfos:         file_proto_paigram_v1_common_proto_enumTypes,
		MessageInfos:      file_proto_paigram_v1_common_proto_msgTypes,
	}.Build()
	File_proto_paigram_v1_common_proto = out.File
	file_proto_paigram_v1_common_proto_goTypes = nil
	file_proto_paigram_v1_common_proto_depIdxs = nil
}
