// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.1
// source: proto/paigram/v1/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户状态枚举
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_PENDING     UserStatus = 1
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 2
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 3
	UserStatus_USER_STATUS_DELETED     UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_PENDING",
		2: "USER_STATUS_ACTIVE",
		3: "USER_STATUS_SUSPENDED",
		4: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_PENDING":     1,
		"USER_STATUS_ACTIVE":      2,
		"USER_STATUS_SUSPENDED":   3,
		"USER_STATUS_DELETED":     4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paigram_v1_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_proto_paigram_v1_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{0}
}

// 用户信息
type User struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrimaryLoginType string                 `protobuf:"bytes,2,opt,name=primary_login_type,json=primaryLoginType,proto3" json:"primary_login_type,omitempty"`
	Status           UserStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=paigram.v1.UserStatus" json:"status,omitempty"`
	LastLoginAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 用户资料
	Profile *UserProfile `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`
	// 用户邮箱列表
	Emails        []*UserEmail `protobuf:"bytes,11,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetPrimaryLoginType() string {
	if x != nil {
		return x.PrimaryLoginType
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *User) GetEmails() []*UserEmail {
	if x != nil {
		return x.Emails
	}
	return nil
}

// 用户资料
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Locale        string                 `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

// 用户邮箱
type UserEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	IsVerified    bool                   `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmail) Reset() {
	*x = UserEmail{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmail) ProtoMessage() {}

func (x *UserEmail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmail.ProtoReflect.Descriptor instead.
func (*UserEmail) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserEmail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserEmail) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserEmail) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UserEmail) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *UserEmail) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

// 获取用户请求
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetUserRequest_Id
	//	*GetUserRequest_Email
	Identifier    isGetUserRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetIdentifier() isGetUserRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetUserRequest) GetId() uint64 {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isGetUserRequest_Identifier interface {
	isGetUserRequest_Identifier()
}

type GetUserRequest_Id struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetUserRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*GetUserRequest_Id) isGetUserRequest_Identifier() {}

func (*GetUserRequest_Email) isGetUserRequest_Identifier() {}

// 获取用户响应
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 批量获取用户请求
type GetUsersByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdsRequest) Reset() {
	*x = GetUsersByIdsRequest{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdsRequest) ProtoMessage() {}

func (x *GetUsersByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersByIdsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 批量获取用户响应
type GetUsersByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdsResponse) Reset() {
	*x = GetUsersByIdsResponse{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdsResponse) ProtoMessage() {}

func (x *GetUsersByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersByIdsResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// 验证用户请求
type VerifyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserRequest) Reset() {
	*x = VerifyUserRequest{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserRequest) ProtoMessage() {}

func (x *VerifyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserRequest.ProtoReflect.Descriptor instead.
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 验证用户响应
type VerifyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserResponse) Reset() {
	*x = VerifyUserResponse{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserResponse) ProtoMessage() {}

func (x *VerifyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserResponse.ProtoReflect.Descriptor instead.
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyUserResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *VerifyUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取用户权限请求
type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserPermissionsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户权限响应
type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserPermissionsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetUserPermissionsResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 更新用户数据请求
type UpdateUserDataRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 可选更新的字段
	DisplayName   *string `protobuf:"bytes,10,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	AvatarUrl     *string `protobuf:"bytes,11,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Bio           *string `protobuf:"bytes,12,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	Locale        *string `protobuf:"bytes,13,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserDataRequest) Reset() {
	*x = UpdateUserDataRequest{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataRequest) ProtoMessage() {}

func (x *UpdateUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserDataRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserDataRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateUserDataRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserDataRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateUserDataRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

// 更新用户数据响应
type UpdateUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserDataResponse) Reset() {
	*x = UpdateUserDataResponse{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserDataResponse) ProtoMessage() {}

func (x *UpdateUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserDataResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 获取用户统计请求
type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserStatsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户统计响应
type GetUserStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginCount         uint32                 `protobuf:"varint,2,opt,name=login_count,json=loginCount,proto3" json:"login_count,omitempty"`
	LastLoginAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	EmailCount         uint32                 `protobuf:"varint,4,opt,name=email_count,json=emailCount,proto3" json:"email_count,omitempty"`
	VerifiedEmailCount uint32                 `protobuf:"varint,5,opt,name=verified_email_count,json=verifiedEmailCount,proto3" json:"verified_email_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	mi := &file_proto_paigram_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserStatsResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserStatsResponse) GetLoginCount() uint32 {
	if x != nil {
		return x.LoginCount
	}
	return 0
}

func (x *GetUserStatsResponse) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *GetUserStatsResponse) GetEmailCount() uint32 {
	if x != nil {
		return x.EmailCount
	}
	return 0
}

func (x *GetUserStatsResponse) GetVerifiedEmailCount() uint32 {
	if x != nil {
		return x.VerifiedEmailCount
	}
	return 0
}

var File_proto_paigram_v1_user_proto protoreflect.FileDescriptor

const file_proto_paigram_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/paigram/v1/user.proto\x12\n" +
	"paigram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12,\n" +
	"\x12primary_login_type\x18\x02 \x01(\tR\x10primaryLoginType\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.paigram.v1.UserStatusR\x06status\x12>\n" +
	"\rlast_login_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x121\n" +
	"\aprofile\x18\n" +
	" \x01(\v2\x17.paigram.v1.UserProfileR\aprofile\x12-\n" +
	"\x06emails\x18\v \x03(\v2\x15.paigram.v1.UserEmailR\x06emails\"\xa2\x01\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\"\xc7\x01\n" +
	"\tUserEmail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12\x1f\n" +
	"\vis_verified\x18\x05 \x01(\bR\n" +
	"isVerified\x12;\n" +
	"\vverified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\"H\n" +
	"\x0eGetUserRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05emailB\f\n" +
	"\n" +
	"identifier\"7\n" +
	"\x0fGetUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.paigram.v1.UserR\x04user\"(\n" +
	"\x14GetUsersByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"?\n" +
	"\x15GetUsersByIdsResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.paigram.v1.UserR\x05users\"E\n" +
	"\x11VerifyUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"j\n" +
	"\x12VerifyUserResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.paigram.v1.UserR\x04user\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"4\n" +
	"\x19GetUserPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"T\n" +
	"\x1aGetUserPermissionsResponse\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"\xe3\x01\n" +
	"\x15UpdateUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12&\n" +
	"\fdisplay_name\x18\n" +
	" \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\v \x01(\tH\x01R\tavatarUrl\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\f \x01(\tH\x02R\x03bio\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\r \x01(\tH\x03R\x06locale\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\r\n" +
	"\v_avatar_urlB\x06\n" +
	"\x04_bioB\t\n" +
	"\a_locale\">\n" +
	"\x16UpdateUserDataResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.paigram.v1.UserR\x04user\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xe3\x01\n" +
	"\x14GetUserStatsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vlogin_count\x18\x02 \x01(\rR\n" +
	"loginCount\x12>\n" +
	"\rlast_login_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x12\x1f\n" +
	"\vemail_count\x18\x04 \x01(\rR\n" +
	"emailCount\x120\n" +
	"\x14verified_email_count\x18\x05 \x01(\rR\x12verifiedEmailCount*\x8e\x01\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13USER_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x02\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x03\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x042\x85\x04\n" +
	"\vUserService\x12B\n" +
	"\aGetUser\x12\x1a.paigram.v1.GetUserRequest\x1a\x1b.paigram.v1.GetUserResponse\x12T\n" +
	"\rGetUsersByIds\x12 .paigram.v1.GetUsersByIdsRequest\x1a!.paigram.v1.GetUsersByIdsResponse\x12K\n" +
	"\n" +
	"VerifyUser\x12\x1d.paigram.v1.VerifyUserRequest\x1a\x1e.paigram.v1.VerifyUserResponse\x12c\n" +
	"\x12GetUserPermissions\x12%.paigram.v1.GetUserPermissionsRequest\x1a&.paigram.v1.GetUserPermissionsResponse\x12W\n" +
	"\x0eUpdateUserData\x12!.paigram.v1.UpdateUserDataRequest\x1a\".paigram.v1.UpdateUserDataResponse\x12Q\n" +
	"\fGetUserStats\x12\x1f.paigram.v1.GetUserStatsRequest\x1a .paigram.v1.GetUserStatsResponseB Z\x1epaigram/internal/grpc/pb/v1;pbb\x06proto3"

var (
	file_proto_paigram_v1_user_proto_rawDescOnce sync.Once
	file_proto_paigram_v1_user_proto_rawDescData []byte
)

func file_proto_paigram_v1_user_proto_rawDescGZIP() []byte {
	file_proto_paigram_v1_user_proto_rawDescOnce.Do(func() {
		file_proto_paigram_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paigram_v1_user_proto_rawDesc), len(file_proto_paigram_v1_user_proto_rawDesc)))
	})
	return file_proto_paigram_v1_user_proto_rawDescData
}

var file_proto_paigram_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_paigram_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_paigram_v1_user_proto_goTypes = []any{
	(UserStatus)(0),                    // 0: paigram.v1.UserStatus
	(*User)(nil),                       // 1: paigram.v1.User
	(*UserProfile)(nil),                // 2: paigram.v1.UserProfile
	(*UserEmail)(nil),                  // 3: paigram.v1.UserEmail
	(*GetUserRequest)(nil),             // 4: paigram.v1.GetUserRequest
	(*GetUserResponse)(nil),            // 5: paigram.v1.GetUserResponse
	(*GetUsersByIdsRequest)(nil),       // 6: paigram.v1.GetUsersByIdsRequest
	(*GetUsersByIdsResponse)(nil),      // 7: paigram.v1.GetUsersByIdsResponse
	(*VerifyUserRequest)(nil),          // 8: paigram.v1.VerifyUserRequest
	(*VerifyUserResponse)(nil),         // 9: paigram.v1.VerifyUserResponse
	(*GetUserPermissionsRequest)(nil),  // 10: paigram.v1.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil), // 11: paigram.v1.GetUserPermissionsResponse
	(*UpdateUserDataRequest)(nil),      // 12: paigram.v1.UpdateUserDataRequest
	(*UpdateUserDataResponse)(nil),     // 13: paigram.v1.UpdateUserDataResponse
	(*GetUserStatsRequest)(nil),        // 14: paigram.v1.GetUserStatsRequest
	(*GetUserStatsResponse)(nil),       // 15: paigram.v1.GetUserStatsResponse
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_proto_paigram_v1_user_proto_depIdxs = []int32{
	0,  // 0: paigram.v1.User.status:type_name -> paigram.v1.UserStatus
	16, // 1: paigram.v1.User.last_login_at:type_name -> google.protobuf.Timestamp
	16, // 2: paigram.v1.User.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: paigram.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: paigram.v1.User.profile:type_name -> paigram.v1.UserProfile
	3,  // 5: paigram.v1.User.emails:type_name -> paigram.v1.UserEmail
	16, // 6: paigram.v1.UserEmail.verified_at:type_name -> google.protobuf.Timestamp
	1,  // 7: paigram.v1.GetUserResponse.user:type_name -> paigram.v1.User
	1,  // 8: paigram.v1.GetUsersByIdsResponse.users:type_name -> paigram.v1.User
	1,  // 9: paigram.v1.VerifyUserResponse.user:type_name -> paigram.v1.User
	1,  // 10: paigram.v1.UpdateUserDataResponse.user:type_name -> paigram.v1.User
	16, // 11: paigram.v1.GetUserStatsResponse.last_login_at:type_name -> google.protobuf.Timestamp
	4,  // 12: paigram.v1.UserService.GetUser:input_type -> paigram.v1.GetUserRequest
	6,  // 13: paigram.v1.UserService.GetUsersByIds:input_type -> paigram.v1.GetUsersByIdsRequest
	8,  // 14: paigram.v1.UserService.VerifyUser:input_type -> paigram.v1.VerifyUserRequest
	10, // 15: paigram.v1.UserService.GetUserPermissions:input_type -> paigram.v1.GetUserPermissionsRequest
	12, // 16: paigram.v1.UserService.UpdateUserData:input_type -> paigram.v1.UpdateUserDataRequest
	14, // 17: paigram.v1.UserService.GetUserStats:input_type -> paigram.v1.GetUserStatsRequest
	5,  // 18: paigram.v1.UserService.GetUser:output_type -> paigram.v1.GetUserResponse
	7,  // 19: paigram.v1.UserService.GetUsersByIds:output_type -> paigram.v1.GetUsersByIdsResponse
	9,  // 20: paigram.v1.UserService.VerifyUser:output_type -> paigram.v1.VerifyUserResponse
	11, // 21: paigram.v1.UserService.GetUserPermissions:output_type -> paigram.v1.GetUserPermissionsResponse
	13, // 22: paigram.v1.UserService.UpdateUserData:output_type -> paigram.v1.UpdateUserDataResponse
	15, // 23: paigram.v1.UserService.GetUserStats:output_type -> paigram.v1.GetUserStatsResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_paigram_v1_user_proto_init() }
func file_proto_paigram_v1_user_proto_init() {
	if File_proto_paigram_v1_user_proto != nil {
		return
	}
	file_proto_paigram_v1_user_proto_msgTypes[3].OneofWrappers = []any{
		(*GetUserRequest_Id)(nil),
		(*GetUserRequest_Email)(nil),
	}
	file_proto_paigram_v1_user_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paigram_v1_user_proto_rawDesc), len(file_proto_paigram_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paigram_v1_user_proto_goTypes,
		DependencyIndexes: file_proto_paigram_v1_user_proto_depIdxs,
		EnumInfos:         file_proto_paigram_v1_user_proto_enumTypes,
		MessageInfos:      file_proto_paigram_v1_user_proto_msgTypes,
	}.Build()
	File_proto_paigram_v1_user_proto = out.File
	file_proto_paigram_v1_user_proto_goTypes = nil
	file_proto_paigram_v1_user_proto_depIdxs = nil
}
