# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from paigram_account_sdk._generated.platform.v2 import control_pb2 as platform_dot_v2_dot_control__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in platform/v2/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlatformControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BindCredential = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/BindCredential',
                request_serializer=platform_dot_v2_dot_control__pb2.BindCredentialRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.BindCredentialResponse.FromString,
                _registered_method=True)
        self.ReplaceCredential = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/ReplaceCredential',
                request_serializer=platform_dot_v2_dot_control__pb2.ReplaceCredentialRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.ReplaceCredentialResponse.FromString,
                _registered_method=True)
        self.RefreshCredential = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/RefreshCredential',
                request_serializer=platform_dot_v2_dot_control__pb2.RefreshCredentialRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.RefreshCredentialResponse.FromString,
                _registered_method=True)
        self.DeleteCredential = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/DeleteCredential',
                request_serializer=platform_dot_v2_dot_control__pb2.DeleteCredentialRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.DeleteCredentialResponse.FromString,
                _registered_method=True)
        self.ApplyAuthorizationFence = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/ApplyAuthorizationFence',
                request_serializer=platform_dot_v2_dot_control__pb2.ApplyAuthorizationFenceRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.ApplyAuthorizationFenceResponse.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/GetOperation',
                request_serializer=platform_dot_v2_dot_control__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.GetOperationResponse.FromString,
                _registered_method=True)
        self.ResolveOperation = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/ResolveOperation',
                request_serializer=platform_dot_v2_dot_control__pb2.ResolveOperationRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.ResolveOperationResponse.FromString,
                _registered_method=True)
        self.GetBindingState = channel.unary_unary(
                '/paigram.platform.v2.PlatformControlService/GetBindingState',
                request_serializer=platform_dot_v2_dot_control__pb2.GetBindingStateRequest.SerializeToString,
                response_deserializer=platform_dot_v2_dot_control__pb2.GetBindingStateResponse.FromString,
                _registered_method=True)


class PlatformControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def BindCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyAuthorizationFence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBindingState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BindCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.BindCredential,
                    request_deserializer=platform_dot_v2_dot_control__pb2.BindCredentialRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.BindCredentialResponse.SerializeToString,
            ),
            'ReplaceCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceCredential,
                    request_deserializer=platform_dot_v2_dot_control__pb2.ReplaceCredentialRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.ReplaceCredentialResponse.SerializeToString,
            ),
            'RefreshCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshCredential,
                    request_deserializer=platform_dot_v2_dot_control__pb2.RefreshCredentialRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.RefreshCredentialResponse.SerializeToString,
            ),
            'DeleteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredential,
                    request_deserializer=platform_dot_v2_dot_control__pb2.DeleteCredentialRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.DeleteCredentialResponse.SerializeToString,
            ),
            'ApplyAuthorizationFence': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyAuthorizationFence,
                    request_deserializer=platform_dot_v2_dot_control__pb2.ApplyAuthorizationFenceRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.ApplyAuthorizationFenceResponse.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=platform_dot_v2_dot_control__pb2.GetOperationRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.GetOperationResponse.SerializeToString,
            ),
            'ResolveOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveOperation,
                    request_deserializer=platform_dot_v2_dot_control__pb2.ResolveOperationRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.ResolveOperationResponse.SerializeToString,
            ),
            'GetBindingState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBindingState,
                    request_deserializer=platform_dot_v2_dot_control__pb2.GetBindingStateRequest.FromString,
                    response_serializer=platform_dot_v2_dot_control__pb2.GetBindingStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paigram.platform.v2.PlatformControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paigram.platform.v2.PlatformControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlatformControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BindCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/BindCredential',
            platform_dot_v2_dot_control__pb2.BindCredentialRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.BindCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/ReplaceCredential',
            platform_dot_v2_dot_control__pb2.ReplaceCredentialRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.ReplaceCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/RefreshCredential',
            platform_dot_v2_dot_control__pb2.RefreshCredentialRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.RefreshCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/DeleteCredential',
            platform_dot_v2_dot_control__pb2.DeleteCredentialRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.DeleteCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyAuthorizationFence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/ApplyAuthorizationFence',
            platform_dot_v2_dot_control__pb2.ApplyAuthorizationFenceRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.ApplyAuthorizationFenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/GetOperation',
            platform_dot_v2_dot_control__pb2.GetOperationRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.GetOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/ResolveOperation',
            platform_dot_v2_dot_control__pb2.ResolveOperationRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.ResolveOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBindingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.platform.v2.PlatformControlService/GetBindingState',
            platform_dot_v2_dot_control__pb2.GetBindingStateRequest.SerializeToString,
            platform_dot_v2_dot_control__pb2.GetBindingStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
