# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from paigram_account_sdk._generated.mihomo.v2 import runtime_pb2 as mihomo_dot_v2_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mihomo/v2/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MihomoRuntimeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribePlatform = channel.unary_unary(
                '/paigram.mihomo.v2.MihomoRuntimeService/DescribePlatform',
                request_serializer=mihomo_dot_v2_dot_runtime__pb2.DescribePlatformRequest.SerializeToString,
                response_deserializer=mihomo_dot_v2_dot_runtime__pb2.DescribePlatformResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/paigram.mihomo.v2.MihomoRuntimeService/GetStatus',
                request_serializer=mihomo_dot_v2_dot_runtime__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.ValidateCredential = channel.unary_unary(
                '/paigram.mihomo.v2.MihomoRuntimeService/ValidateCredential',
                request_serializer=mihomo_dot_v2_dot_runtime__pb2.ValidateCredentialRequest.SerializeToString,
                response_deserializer=mihomo_dot_v2_dot_runtime__pb2.ValidateCredentialResponse.FromString,
                _registered_method=True)
        self.ListProfiles = channel.unary_unary(
                '/paigram.mihomo.v2.MihomoRuntimeService/ListProfiles',
                request_serializer=mihomo_dot_v2_dot_runtime__pb2.ListProfilesRequest.SerializeToString,
                response_deserializer=mihomo_dot_v2_dot_runtime__pb2.ListProfilesResponse.FromString,
                _registered_method=True)
        self.GetPrimaryProfile = channel.unary_unary(
                '/paigram.mihomo.v2.MihomoRuntimeService/GetPrimaryProfile',
                request_serializer=mihomo_dot_v2_dot_runtime__pb2.GetPrimaryProfileRequest.SerializeToString,
                response_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetPrimaryProfileResponse.FromString,
                _registered_method=True)
        self.GetAuthKey = channel.unary_unary(
                '/paigram.mihomo.v2.MihomoRuntimeService/GetAuthKey',
                request_serializer=mihomo_dot_v2_dot_runtime__pb2.GetAuthKeyRequest.SerializeToString,
                response_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetAuthKeyResponse.FromString,
                _registered_method=True)
        self.GetDevice = channel.unary_unary(
                '/paigram.mihomo.v2.MihomoRuntimeService/GetDevice',
                request_serializer=mihomo_dot_v2_dot_runtime__pb2.GetDeviceRequest.SerializeToString,
                response_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetDeviceResponse.FromString,
                _registered_method=True)


class MihomoRuntimeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def DescribePlatform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrimaryProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MihomoRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribePlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribePlatform,
                    request_deserializer=mihomo_dot_v2_dot_runtime__pb2.DescribePlatformRequest.FromString,
                    response_serializer=mihomo_dot_v2_dot_runtime__pb2.DescribePlatformResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetStatusRequest.FromString,
                    response_serializer=mihomo_dot_v2_dot_runtime__pb2.GetStatusResponse.SerializeToString,
            ),
            'ValidateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCredential,
                    request_deserializer=mihomo_dot_v2_dot_runtime__pb2.ValidateCredentialRequest.FromString,
                    response_serializer=mihomo_dot_v2_dot_runtime__pb2.ValidateCredentialResponse.SerializeToString,
            ),
            'ListProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfiles,
                    request_deserializer=mihomo_dot_v2_dot_runtime__pb2.ListProfilesRequest.FromString,
                    response_serializer=mihomo_dot_v2_dot_runtime__pb2.ListProfilesResponse.SerializeToString,
            ),
            'GetPrimaryProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimaryProfile,
                    request_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetPrimaryProfileRequest.FromString,
                    response_serializer=mihomo_dot_v2_dot_runtime__pb2.GetPrimaryProfileResponse.SerializeToString,
            ),
            'GetAuthKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthKey,
                    request_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetAuthKeyRequest.FromString,
                    response_serializer=mihomo_dot_v2_dot_runtime__pb2.GetAuthKeyResponse.SerializeToString,
            ),
            'GetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevice,
                    request_deserializer=mihomo_dot_v2_dot_runtime__pb2.GetDeviceRequest.FromString,
                    response_serializer=mihomo_dot_v2_dot_runtime__pb2.GetDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paigram.mihomo.v2.MihomoRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paigram.mihomo.v2.MihomoRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MihomoRuntimeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DescribePlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v2.MihomoRuntimeService/DescribePlatform',
            mihomo_dot_v2_dot_runtime__pb2.DescribePlatformRequest.SerializeToString,
            mihomo_dot_v2_dot_runtime__pb2.DescribePlatformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v2.MihomoRuntimeService/GetStatus',
            mihomo_dot_v2_dot_runtime__pb2.GetStatusRequest.SerializeToString,
            mihomo_dot_v2_dot_runtime__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v2.MihomoRuntimeService/ValidateCredential',
            mihomo_dot_v2_dot_runtime__pb2.ValidateCredentialRequest.SerializeToString,
            mihomo_dot_v2_dot_runtime__pb2.ValidateCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v2.MihomoRuntimeService/ListProfiles',
            mihomo_dot_v2_dot_runtime__pb2.ListProfilesRequest.SerializeToString,
            mihomo_dot_v2_dot_runtime__pb2.ListProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrimaryProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v2.MihomoRuntimeService/GetPrimaryProfile',
            mihomo_dot_v2_dot_runtime__pb2.GetPrimaryProfileRequest.SerializeToString,
            mihomo_dot_v2_dot_runtime__pb2.GetPrimaryProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v2.MihomoRuntimeService/GetAuthKey',
            mihomo_dot_v2_dot_runtime__pb2.GetAuthKeyRequest.SerializeToString,
            mihomo_dot_v2_dot_runtime__pb2.GetAuthKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v2.MihomoRuntimeService/GetDevice',
            mihomo_dot_v2_dot_runtime__pb2.GetDeviceRequest.SerializeToString,
            mihomo_dot_v2_dot_runtime__pb2.GetDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
