# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from paigram_account_sdk._generated.account.v1 import bot_access_pb2 as account_dot_v1_dot_bot__access__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in account/v1/bot_access_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BotAccessServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveBotUser = channel.unary_unary(
                '/paigram.v1.BotAccessService/ResolveBotUser',
                request_serializer=account_dot_v1_dot_bot__access__pb2.ResolveBotUserRequest.SerializeToString,
                response_deserializer=account_dot_v1_dot_bot__access__pb2.ResolveBotUserResponse.FromString,
                _registered_method=True)
        self.ListAccessibleBindings = channel.unary_unary(
                '/paigram.v1.BotAccessService/ListAccessibleBindings',
                request_serializer=account_dot_v1_dot_bot__access__pb2.ListAccessibleBindingsRequest.SerializeToString,
                response_deserializer=account_dot_v1_dot_bot__access__pb2.ListAccessibleBindingsResponse.FromString,
                _registered_method=True)
        self.GetPlatformRuntimeRoute = channel.unary_unary(
                '/paigram.v1.BotAccessService/GetPlatformRuntimeRoute',
                request_serializer=account_dot_v1_dot_bot__access__pb2.GetPlatformRuntimeRouteRequest.SerializeToString,
                response_deserializer=account_dot_v1_dot_bot__access__pb2.GetPlatformRuntimeRouteResponse.FromString,
                _registered_method=True)
        self.IssueServiceTicket = channel.unary_unary(
                '/paigram.v1.BotAccessService/IssueServiceTicket',
                request_serializer=account_dot_v1_dot_bot__access__pb2.IssueServiceTicketRequest.SerializeToString,
                response_deserializer=account_dot_v1_dot_bot__access__pb2.IssueServiceTicketResponse.FromString,
                _registered_method=True)


class BotAccessServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ResolveBotUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessibleBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatformRuntimeRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueServiceTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotAccessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveBotUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveBotUser,
                    request_deserializer=account_dot_v1_dot_bot__access__pb2.ResolveBotUserRequest.FromString,
                    response_serializer=account_dot_v1_dot_bot__access__pb2.ResolveBotUserResponse.SerializeToString,
            ),
            'ListAccessibleBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessibleBindings,
                    request_deserializer=account_dot_v1_dot_bot__access__pb2.ListAccessibleBindingsRequest.FromString,
                    response_serializer=account_dot_v1_dot_bot__access__pb2.ListAccessibleBindingsResponse.SerializeToString,
            ),
            'GetPlatformRuntimeRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatformRuntimeRoute,
                    request_deserializer=account_dot_v1_dot_bot__access__pb2.GetPlatformRuntimeRouteRequest.FromString,
                    response_serializer=account_dot_v1_dot_bot__access__pb2.GetPlatformRuntimeRouteResponse.SerializeToString,
            ),
            'IssueServiceTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueServiceTicket,
                    request_deserializer=account_dot_v1_dot_bot__access__pb2.IssueServiceTicketRequest.FromString,
                    response_serializer=account_dot_v1_dot_bot__access__pb2.IssueServiceTicketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paigram.v1.BotAccessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paigram.v1.BotAccessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotAccessService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveBotUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.v1.BotAccessService/ResolveBotUser',
            account_dot_v1_dot_bot__access__pb2.ResolveBotUserRequest.SerializeToString,
            account_dot_v1_dot_bot__access__pb2.ResolveBotUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccessibleBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.v1.BotAccessService/ListAccessibleBindings',
            account_dot_v1_dot_bot__access__pb2.ListAccessibleBindingsRequest.SerializeToString,
            account_dot_v1_dot_bot__access__pb2.ListAccessibleBindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlatformRuntimeRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.v1.BotAccessService/GetPlatformRuntimeRoute',
            account_dot_v1_dot_bot__access__pb2.GetPlatformRuntimeRouteRequest.SerializeToString,
            account_dot_v1_dot_bot__access__pb2.GetPlatformRuntimeRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueServiceTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.v1.BotAccessService/IssueServiceTicket',
            account_dot_v1_dot_bot__access__pb2.IssueServiceTicketRequest.SerializeToString,
            account_dot_v1_dot_bot__access__pb2.IssueServiceTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
