# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from paigram_account_sdk._generated.mihomo.v1 import credential_pb2 as mihomo_dot_v1_dot_credential__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mihomo/v1/credential_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MihomoCredentialServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCredentialSummary = channel.unary_unary(
                '/paigram.mihomo.v1.MihomoCredentialService/GetCredentialSummary',
                request_serializer=mihomo_dot_v1_dot_credential__pb2.GetCredentialSummaryRequest.SerializeToString,
                response_deserializer=mihomo_dot_v1_dot_credential__pb2.GetCredentialSummaryResponse.FromString,
                _registered_method=True)


class MihomoCredentialServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCredentialSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MihomoCredentialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCredentialSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentialSummary,
                    request_deserializer=mihomo_dot_v1_dot_credential__pb2.GetCredentialSummaryRequest.FromString,
                    response_serializer=mihomo_dot_v1_dot_credential__pb2.GetCredentialSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paigram.mihomo.v1.MihomoCredentialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paigram.mihomo.v1.MihomoCredentialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MihomoCredentialService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCredentialSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paigram.mihomo.v1.MihomoCredentialService/GetCredentialSummary',
            mihomo_dot_v1_dot_credential__pb2.GetCredentialSummaryRequest.SerializeToString,
            mihomo_dot_v1_dot_credential__pb2.GetCredentialSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
