# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mihomo/v1/credential.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mihomo/v1/credential.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amihomo/v1/credential.proto\x12\x11paigram.mihomo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n\rDeviceSummary\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tdevice_fp\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x01(\t\x12\x10\n\x08is_valid\x18\x04 \x01(\x08\x12\x30\n\x0clast_seen_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa3\x01\n\x0eProfileSummary\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1b\n\x13platform_account_id\x18\x02 \x01(\t\x12\x10\n\x08game_biz\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x11\n\tplayer_id\x18\x05 \x01(\t\x12\x10\n\x08nickname\x18\x06 \x01(\t\x12\r\n\x05level\x18\x07 \x01(\x05\x12\x12\n\nis_default\x18\x08 \x01(\x08\"R\n\x1bGetCredentialSummaryRequest\x12\x16\n\x0eservice_ticket\x18\x01 \x01(\t\x12\x1b\n\x13platform_account_id\x18\x02 \x01(\t\"\xc6\x02\n\x1cGetCredentialSummaryResponse\x12\x1b\n\x13platform_account_id\x18\x01 \x01(\t\x12\x33\n\x06status\x18\x02 \x01(\x0e\x32#.paigram.mihomo.v1.CredentialStatus\x12\x35\n\x11last_validated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x11last_refreshed_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x07\x64\x65vices\x18\x05 \x03(\x0b\x32 .paigram.mihomo.v1.DeviceSummary\x12\x33\n\x08profiles\x18\x06 \x03(\x0b\x32!.paigram.mihomo.v1.ProfileSummary*\xbb\x01\n\x10\x43redentialStatus\x12!\n\x1d\x43REDENTIAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x43REDENTIAL_STATUS_ACTIVE\x10\x01\x12\x1d\n\x19\x43REDENTIAL_STATUS_EXPIRED\x10\x02\x12\x1d\n\x19\x43REDENTIAL_STATUS_INVALID\x10\x03\x12(\n$CREDENTIAL_STATUS_CHALLENGE_REQUIRED\x10\x04\x32\x92\x01\n\x17MihomoCredentialService\x12w\n\x14GetCredentialSummary\x12..paigram.mihomo.v1.GetCredentialSummaryRequest\x1a/.paigram.mihomo.v1.GetCredentialSummaryResponseBSZQgithub.com/PaiGramTeam/paigram-account-center/contracts/gen/go/mihomo/v1;mihomov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mihomo.v1.credential_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZQgithub.com/PaiGramTeam/paigram-account-center/contracts/gen/go/mihomo/v1;mihomov1'
  _globals['_CREDENTIALSTATUS']._serialized_start=807
  _globals['_CREDENTIALSTATUS']._serialized_end=994
  _globals['_DEVICESUMMARY']._serialized_start=83
  _globals['_DEVICESUMMARY']._serialized_end=225
  _globals['_PROFILESUMMARY']._serialized_start=228
  _globals['_PROFILESUMMARY']._serialized_end=391
  _globals['_GETCREDENTIALSUMMARYREQUEST']._serialized_start=393
  _globals['_GETCREDENTIALSUMMARYREQUEST']._serialized_end=475
  _globals['_GETCREDENTIALSUMMARYRESPONSE']._serialized_start=478
  _globals['_GETCREDENTIALSUMMARYRESPONSE']._serialized_end=804
  _globals['_MIHOMOCREDENTIALSERVICE']._serialized_start=997
  _globals['_MIHOMOCREDENTIALSERVICE']._serialized_end=1143
# @@protoc_insertion_point(module_scope)
